### ISSUE TITLE
data/make_data_loader.py not included in repo

### ISSUE THREAD

**Issue by Oewyn** [michuanhaohao/reid-strong-baseline#1]
I'm trying to train the baseline model on dukeMTMC-reid and when I follow the README.md instructions I see the error: 

    $ python3 tools/train.py --config_file='configs/softmax_triplet_with_center.yml' MODEL.DEVICE_ID "('0')" DATASETS.NAMES "('dukemtmc')" OUTPUT_DIR "('dukemtmc-reid_0')"

    Traceback (most recent call last):
      File "tools/train.py", line 15, in <module>
        from data import make_data_loader
    ImportError: cannot import name 'make_data_loader'

It seems like make_data_loader.py was not included in the github repo, both tools/train.py and tools/test.py reference make_data_loader.

**Comment by michuanhaohao** [comment]
@Oewyn I am sorry! I forgot to upload it. Please 'git pull' and try again. 
I recommend that you save the dataset in another folder and input the file path into the configure file.
