### ISSUE TITLE
AttributeError: 'Baseline' object has no attribute 'copy'

### ISSUE THREAD

**Issue by liuchanfeng165** [michuanhaohao/reid-strong-baseline#100]
when loading model,mabe win donst support it......
'Traceback (most recent call last):
  File "tools/train.py", line 184, in <module>
    main()
  File "tools/train.py", line 180, in main
    train(cfg)
  File "tools/train.py", line 108, in train
    model.load_state_dict(torch.load(cfg.MODEL.PRETRAIN_PATH))
  File "E:\Python36\lib\site-packages\torch\nn\modules\module.py", line 752, in
load_state_dict
    state_dict = state_dict.copy()
  File "E:\Python36\lib\site-packages\torch\nn\modules\module.py", line 540, in
__getattr__
    type(self).__name__, name))
AttributeError: 'Baseline' object has no attribute 'copy'
'

**Comment by liuchanfeng165** [comment]
been sovled~

**Comment by PAUPAUPAUL** [comment]
Hi, i meet the same problem, how did you solve this problem?

**Comment by wei-yuma** [comment]
@liuchanfeng165 Can you share your solution? I meet this problem too. Thank you!

**Comment by ggyybb** [comment]
> @liuchanfeng165 Can you share your solution? I meet this problem too. Thank you!

你解决了么请问

**Comment by finger-monkey** [comment]
> been sovled~

Could you tell me how to solve this problem?

**Comment by Felixllq** [comment]
Could you tell me how to solve this problem?
