### ISSUE TITLE
pytorch模型转为caffe模型之后mAP下降10个点

### ISSUE THREAD

**Issue by LilySys** [michuanhaohao/reid-strong-baseline#107]
罗博士，您好，当我把pytorch模型转为caffe模型之后，在同样的预处理情况下测试同样的数据集，caffe模型下降10个点，我已排除模型不一致的问题，唯一不相同的点是，pytorch用pil进行图像的预处理，python使用的opencv进行图像的预处理，不知您是否遇到过，能否提供一些思路？

**Comment by michuanhaohao** [comment]
我印象中PIL读图和opencv读图的通道是不一样的，一个是RGB，一个是BGR还是什么

**Comment by buptlj** [comment]
pil和opencv读图像素值会有一定差异，好像跟他们调用的图片解码的库有关，而且pil和opencv的resize结果也不一样，即使都用双线性插值也不一样。但是这些差异应该不至于下降10个点。之前用libtorch在c++下试过，和python的结果差0.5个点左右。

**Comment by LilySys** [comment]
> pil和opencv读图像素值会有一定差异，好像跟他们调用的图片解码的库有关，而且pil和opencv的resize结果也不一样，即使都用双线性插值也不一样。但是这些差异应该不至于下降10个点。之前用libtorch在c++下试过，和python的结果差

**Comment by LilySys** [comment]
> pil和opencv读图像素值会有一定差异，好像跟他们调用的图片解码的库有关，而且pil和opencv的resize结果也不一样，即使都用双线性插值也不一样。但是这些差异应该不至于下降10个点。之前用libtorch在c++下试过，和python的结果差0.5个点左右。

我测试的结论也与您的结论一致，但是还是差很多，不知您对pil与opencv解码是否有了解？

**Comment by LilySys** [comment]
> 我印象中PIL读图和opencv读图的通道是不一样的，一个是RGB，一个是BGR还是什么

测试时opencv已把opencv的BGR换成了RGB了。

**Comment by LilySys** [comment]
> pil和opencv读图像素值会有一定差异，好像跟他们调用的图片解码的库有关，而且pil和opencv的resize结果也不一样，即使都用双线性插值也不一样。但是这些差异应该不至于下降10个点。之前用libtorch在c++下试过，和python的结果差0.5个点左右。

测试时已把opencv的BGR换成了RGB了。

**Comment by buptlj** [comment]
差10个点应该不是pil和opencv的差异导致的。我试过训练时读图和数据增强全都用opencv，然后用libtorch在c++下测试，这样两边都是用opencv，数据输入到网络之前是一样的，输出的feature也基本一致，只在小数点后6位个别值不一样，不过不影响结果。
你可以用同样的数据输入到pytorch模型和转换后的caffe模型，看看各个层的输出是否一样，是不是模型转换有问题，如果模型转换后没问题，那可以考虑在训练时使用opencv，不用pil。

**Comment by LilySys** [comment]
我开始使用同样的输入数据输入pytorch模型和转换后的caffe模型验证过，输出一致，现在也准备训练采用opencv与数据增强。冒昧问一下，关于训练采用opencv是否有在github开放？

**Comment by buptlj** [comment]
已经有很好的开源的数据增强的库了，可以试试 https://github.com/albu/albumentations

**Comment by LilySys** [comment]
> 已经有很好的开源的数据增强的库了，可以试试 https://github.com/albu/albumentations

谢谢
