### ISSUE TITLE
how to resume?

### ISSUE THREAD

**Issue by wei-yuma** [michuanhaohao/reid-strong-baseline#108]

**Comment by michuanhaohao** [comment]
Please try to use the model checkpoint. You might use the optimizer checkpoint.

**Comment by wei-yuma** [comment]
@michuanhaohao yes,I have know how to do it. But I met a problem, AttributeError: 'Baseline' object has no attribute 'copy'. My torch version is 1.1.0. Can you give me some advice?

**Comment by michuanhaohao** [comment]
First, please check you used model checkpoint, not optimizer checkpoint.

Second, you can refer to https://github.com/michuanhaohao/reid-strong-baseline/issues/85 .
