### ISSUE TITLE
train own dataset

### ISSUE THREAD

**Issue by cendelian** [michuanhaohao/reid-strong-baseline#110]
我的数据集有train_set/ query/ gallery 三个。
其中train_set下面的图片名字是一串数字，比如00074877.png, 没有id、camid信息
有一个单独的train_list 有图片名字和对应的id，没有camid信息。

我怎么将我的数据应用到这个baselaine呢? 我看 data/dataset下面的.py文件都是组合img、id、camid 返回

**Comment by michuanhaohao** [comment]
Please refer to https://github.com/michuanhaohao/reid-strong-baseline/issues/89

**Comment by cendelian** [comment]
> Please refer to #89

thanks.
the work support market1501 & veri & msmt17......
i want to know whether the work also supoort the data type of vehicleid data?

**Comment by michuanhaohao** [comment]
暂时不支持，不过自己写一个很快的，参考一下别的数据集的py文件写一下，return一个相同格式的list就行

**Comment by H-YunHui** [comment]
@michuanhaohao , 论文中说在进行跨域实验时效果较差，你们有没有尝试在多个数据集上训，在单个数据集上测试？ 如果有，结果如何呀？如果没有，那这种集合多个数据集的训练方式是否合理，需要注意些什么？
谢谢！

**Comment by michuanhaohao** [comment]
@H-YunHui 融合多个数据集，可能跨域会涨点一点。不过学术论文需要公平的比较，所以学术论文一般不会融合多个数据集
