### ISSUE TITLE
关于re-ranking代码的疑问

### ISSUE THREAD

**Issue by zhxun00cn** [michuanhaohao/reid-strong-baseline#111]
注意到re-ranking的代码作者应该是作者您，我仔细看了下，感觉和论文中的思想不是完全相同，所以我想问几个问题：

1. 代码第46行
` original_dist = np.transpose(original_dist / np.max(original_dist, axis=0))`
对距离矩阵如此处理的目的是什么？处理后，距离矩阵已经不是对称的了，并且转置后每一行的元素放缩的scale都不同

2. 代码48行
`initial_rank = np.argsort(original_dist).astype(np.int32)`
对整个query和gallery进行排序，会出现查询样本的k1互近邻中出现查询集样本，这和论文并不一致

3. 代码第71行
`V[i, k_reciprocal_expansion_index] = weight / np.sum(weight)  `
求每个样本的reci-feature, 除以了负指数的和，这和论文中也不相同

4. 代码第93行
`jaccard_dist[i] = 1 - temp_min / (2 - temp_min) `
这个距离的计算，因个人能力有限，没有能力推出是否和论文中计算方法等价。

想问一下，这几个地方算法实现的思路是什么？

望回复，非常感谢！

**Comment by michuanhaohao** [comment]
这是我两年前翻译的钟准matlab版本的代码，细节想不太起来，但是每一行代码都是翻译自MATLAB的代码，每一行代码都保持和MATLAB版本输出一致，所以实现细节你可以去钟准的原始代码下咨询。

我的代码里面可以找到原始仓库的链接

**Comment by zhxun00cn** [comment]
> 这是我两年前翻译的钟准matlab版本的代码，细节想不太起来，但是每一行代码都是翻译自MATLAB的代码，每一行代码都保持和MATLAB版本输出一致，所以实现细节你可以去钟准的原始代码下咨询。
> 
> 我的代码里面可以找到原始仓库的链接

非常感谢！
