### ISSUE TITLE
Dimension of features

### ISSUE THREAD

**Issue by wencaizhong** [michuanhaohao/reid-strong-baseline#112]
Hi, is there any design considerations about the 2048 dimensional embeddings?  When I added a linear layer after GAP to reduce the feature's dimension (widely adopted in other works), the performance dropped by 1.5% in mAP.

**Comment by michuanhaohao** [comment]
ResNet50 outputs a feature map (with a shape of 2048*H*W). Directly reducing the dimension of feature may degrade performance because larger features have better capacity.
