### ISSUE TITLE
训练数据读取问题（market1501）

### ISSUE THREAD

**Issue by bochuanwu** [michuanhaohao/reid-strong-baseline#116]
请问关于market1501， 其中含有很多只有两三张图片的类别，
您的代码当中 self.num_pids_per_batch小于设定值（默认为4）的是不是就不读取了，是不是不太好呀

**Comment by shaoniangu** [comment]
Hi. 首先这个问题应该考虑的是self.num_instance的设定值会不会有影响，然后这些图片数小于设定值的类别也是考虑进来的。请仔细查看sampler，sampler中有一句：
```
idxs = copy.deepcopy(self.index_dic[pid])
if len(idxs) < self.num_instances:
    idxs = np.random.choice(idxs, size=self.num_instances, replace=True)
```
是允许重复的随机选择哈。

**Comment by bochuanwu** [comment]
> Hi. 首先这个问题应该考虑的是self.num_instance的设定值会不会有影响，然后这些图片数小于设定值的类别也是考虑进来的。请仔细查看sampler，sampler中有一句：
> 
> ```
> idxs = copy.deepcopy(self.index_dic[pid])
> if len(idxs) < self.num_instances:
>     idxs = np.random.choice(idxs, size=self.num_instances, replace=True)
> ```
> 
> 是允许重复的随机选择哈。

谢谢啦 没看那么仔细哈哈
