### ISSUE TITLE
resnet50 implementation

### ISSUE THREAD

**Issue by mxl1990** [michuanhaohao/reid-strong-baseline#117]
I found your code in resnet50 as following

```
def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        # x = self.relu(x)    # add missed relu
        x = self.maxpool(x)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        return x
```
why this relu activation function after conv1 and bn1 is commted by you,
I found this relu is in torchvision.models.resnet code, I want to know this reason, has this relu effect on final results?

**Comment by shaoniangu** [comment]
Hi. Yeah, we missed this relu in our early version and the issue # 4 also talks about this relu. We have done experiments whose results show that this relu does not have much impact on the final result. We keep it missed just to keep the origin version of our codes and we will repair it in the future.
