### ISSUE TITLE
调用自己训练好的模型报错AttributeError: 'Baseline' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Scheaven** [michuanhaohao/reid-strong-baseline#124]
我已经搞定了。谢谢

**Comment by Scheaven** [comment]
加载您提供的模型map低的原因我已经找到了。
我自己训练的模型无法加载的问题仍然无法解决。
我训练的过程中生成了model和optimizer两类模型，我的理解是optimizer用来继续训练时重新加载的。而在评估测试或者展示demo时仅仅使用model即可，但是我无法成功

**Comment by michuanhaohao** [comment]
好的

**Comment by Hanswufe** [comment]
你好，您可以分享一下怎么解决的吗，谢谢@Scheaven

**Comment by ggyybb** [comment]
> 我已经搞定了。谢谢

能问一下怎么搞定的吗！我找了很多了，都搞不定

**Comment by finger-monkey** [comment]
> 我已经搞定了。谢谢

请问可以告诉我们该如何解决这个问题吗？

**Comment by GJTNB** [comment]
> 好的
请问该怎么解决
