### ISSUE TITLE
BNNeck initialization

### ISSUE THREAD

**Issue by JingweiZhang12** [michuanhaohao/reid-strong-baseline#125]
why there is no shift in your BNNeck initialization?
'self.bottleneck.bias.requires_grad_(False)  # no shift'

**Comment by michuanhaohao** [comment]
Our original intention is to hope that the features can be distributed Gaussianly in the hyper-sphere. But some more experiments show that bias does not influence the performance a lot.

**Comment by JingweiZhang12** [comment]
Thanks!
