### ISSUE TITLE
why does it not norm the global_feat in triplet loss?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [michuanhaohao/reid-strong-baseline#126]
i see the code sets `normalize_feature=False` by default in [triplet loss](https://github.com/michuanhaohao/reid-strong-baseline/blob/master/layers/triplet_loss.py#L105), and uses the default value in [make_loss](https://github.com/michuanhaohao/reid-strong-baseline/blob/master/layers/__init__.py#L13). why not norm the global_feat?

**Comment by michuanhaohao** [comment]
Because we find that constraining feature distributed on hyper-sphere reduces performance. Unconstrained distribution in the embedding space is more suitable for the triplet loss.
