### ISSUE TITLE
Continue/resume training

### ISSUE THREAD

**Issue by Ehsan-Yaghoubi** [michuanhaohao/reid-strong-baseline#128]
I'm using `pytorch-ignite==0.1.2` , `torchvision==0.4.0+cu92` and `torch==1.2.0+cu92`, and I have trained the model for 120 epochs. Now, I would like to **continue training** for more epochs. I have modified the `.yml` and also `configu.py` file as:
```
PRETRAIN_CHOICE: 'self'   ### I changed the 'imagenet' to 'self'
PRETRAIN_PATH: '/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/tools/RESULTS_1/resnet50_model_120.pth'
```
 file, but I got this error. Could you please tell me how can I continue training and why I have run to this error?

```
.
.
.
Train without center loss, the loss type is triplet
label smooth on, numclasses: 1295
Start epoch: 120
Path to the checkpoint of optimizer: /media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/tools/RESULTS_1/resnet50_optimizer_120.pth
Traceback (most recent call last):
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/tools/train.py", line 156, in <module>
    main()
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/tools/train.py", line 152, in main
    train(cfg)
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/tools/train.py", line 46, in train
    model.load_state_dict(torch.load(cfg.MODEL.PRETRAIN_PATH))
  File "/home/eshan/.virtualenvs/baseline_person_reidentification/lib/python3.5/site-packages/torch/nn/modules/module.py", line 818, in load_state_dict
    state_dict = state_dict.copy()
  File "/home/eshan/.virtualenvs/baseline_person_reidentification/lib/python3.5/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'Baseline' object has no attribute 'copy'

Process finished with exit code 1
```
I debugged the program and realized that the error comes from these lines:
```
model.load_state_dict(torch.load(cfg.MODEL.PRETRAIN_PATH)) # It cannot copy the 'stase_dict'
optimizer.load_state_dict(torch.load(path_to_optimizer))
```
I have changed the above code to the below code and its working now:
```
            model=torch.load(cfg.MODEL.PRETRAIN_PATH)
            optimizer=torch.load(path_to_optimizer)
```
**But, is it correct? I am not sure that I have done the right thing.**

**Comment by michuanhaohao** [comment]
Please distinguish the model's checkpoint and the optimizer's checkpoint. You loaded the optimizer's checkpoint.

**Comment by okjer** [comment]
我也遇到了这个问题，现在还没有解决，我使用Test中加载模型的方法加载了模型，但是无法加载optimizer,请问怎么解决，为什么会出现这种问题，非常感谢

**Comment by okjer** [comment]
@michuanhaohao

**Comment by okjer** [comment]
@michuanhaohao Ithink he is right,look at this 
def _internal_save(self, obj, path):
        if not self._save_as_state_dict:
            torch.save(obj, path)
        else:
            if not hasattr(obj, "state_dict") or not callable(obj.state_dict):
                raise ValueError("Object should have `state_dict` method")
            torch.save(obj.state_dict(), path)
self._save_as_state_dict = False,
so we should use to load the model an optimizer,maybe your code have some bugs,I  change the code an it works
        model = torch.load(cfg.MODEL.PRETRAIN_PATH)
        optimizer = torch.load(path_to_optimizer)
        center_criterion = torch.load(path_to_center_param)
        optimizer_center = torch.load(path_to_optimizer_center)

**Comment by michuanhaohao** [comment]
Thank you, we will check it.

**Comment by tangsipeng** [comment]
@okjer   i chang the code like you, but i found error

File "/home/tangsipeng/mot/reid/reid-strong_bl/reid-strong-baseline-master/engine/trainer.py", line 92, in _update
    param.grad.data *= (1. / cetner_loss_weight)
AttributeError: 'NoneType' object has no attribute 'data'

then i print param 

for param in center_criterion.parameters():
      print(param)
      param.grad.data *= (1. / cetner_loss_weight)
Parameter containing:
tensor([[0.0827, 0.0711, 0.0590,  ..., 0.0646, 0.0685, 0.0122],
        [0.0678, 0.0787, 0.1088,  ..., 0.0678, 0.0872, 0.0117],
        [0.0635, 0.0587, 0.0687,  ..., 0.0554, 0.0997, 0.0142],
        ...,
        [0.0656, 0.0938, 0.0610,  ..., 0.0546, 0.0710, 0.0128],
        [0.0683, 0.1340, 0.0511,  ..., 0.0503, 0.0704, 0.0132],
        [0.0689, 0.0752, 0.0787,  ..., 0.0470, 0.0615, 0.0177]],
       device='cuda:0', requires_grad=True)

it seems nothing wrong , but  i dont't know why , param.grad is None

**Comment by okjer** [comment]
> @okjer i chang the code like you, but i found error
> 
> File "/home/tangsipeng/mot/reid/reid-strong_bl/reid-strong-baseline-master/engine/trainer.py", line 92, in _update
> param.grad.data *= (1. / cetner_loss_weight)
> AttributeError: 'NoneType' object has no attribute 'data'
> 
> then i print param
> 
> for param in center_criterion.parameters():
> print(param)
> param.grad.data *= (1. / cetner_loss_weight)
> Parameter containing:
> tensor([[0.0827, 0.0711, 0.0590, ..., 0.0646, 0.0685, 0.0122],
> [0.0678, 0.0787, 0.1088, ..., 0.0678, 0.0872, 0.0117],
> [0.0635, 0.0587, 0.0687, ..., 0.0554, 0.0997, 0.0142],
> ...,
> [0.0656, 0.0938, 0.0610, ..., 0.0546, 0.0710, 0.0128],
> [0.0683, 0.1340, 0.0511, ..., 0.0503, 0.0704, 0.0132],
> [0.0689, 0.0752, 0.0787, ..., 0.0470, 0.0615, 0.0177]],
> device='cuda:0', requires_grad=True)
> 
> it seems nothing wrong , but i dont't know why , param.grad is None

I didn't solve the program too,I don't konw why

**Comment by abcdvzz** [comment]
@okjer @tangsipeng Have u guys solved the problem now? It seems that resuming training without center loss is ok by modifying `model.load_state_dict(torch.load(cfg.MODEL.PRETRAIN_PATH)) # It cannot copy the 'stase_dict'
optimizer.load_state_dict(torch.load(path_to_optimizer))` to ` model=torch.load(cfg.MODEL.PRETRAIN_PATH)
            optimizer=torch.load(path_to_optimizer)`.
But resuming training with center loss is not ok by modifying it the same way. @michuanhaohao  Dr Luo, have you solved the bug here now?

**Comment by sun-md** [comment]
@abcdvzz @okjer @tangsipeng 

     `model.load_state_dict(torch.load(cfg.MODEL.PRETRAIN_PATH))
      optimizer.load_state_dict(torch.load(path_to_optimizer))
      center_criterion.load_state_dict(torch.load(path_to_center_param))
      optimizer_center.load_state_dict(torch.load(path_to_optimizer_center))`

I have changed the above code to the below code:

     `model = load_param(model, cfg.MODEL.PRETRAIN_PATH)
      optimizer = torch.load(path_to_optimizer)
      center_criterion = load_param(center_criterion, path_to_center_param)
      optimizer_center = torch.load(path_to_optimizer_center)`

and added "load_param" code:

     `def load_param(pretrain, trained_path):
          param_dict = torch.load(trained_path)
          for k, v in param_dict.state_dict().items():
              pretrain.state_dict()[k].copy_(param_dict.state_dict()[k])
          return pretrain`

Its working, but I can't verify that the loaded way is correct. @michuanhaohao

**Comment by 331319341** [comment]
我也遇到这个问题
