### ISSUE TITLE
关于save_interval的问题

### ISSUE THREAD

**Issue by DJacobJiang** [michuanhaohao/reid-strong-baseline#130]
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    train(cfg)
  File "tools/train.py", line 113, in train
    start_epoch     # add for using self trained model
  File ".\engine\trainer.py", line 235, in do_train_with_center
    checkpointer = ModelCheckpoint(output_dir, cfg.MODEL.NAME, checkpoint_period, Events.ITERATION_STARTED(every=1000),n_saved=10, require_empty=False)
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\pytorch_ignite-0.3.0-py3.7.egg\ignite\handlers\checkpoint.py", line 371, in __init__
ValueError: Argument save_interval is deprecated and should be None. Please, use events filtering instead, e.g. Events.ITERATION_STARTED(every=1000)

**Comment by michuanhaohao** [comment]
你安装的ignite和pytorch的版本是否正确？

**Comment by DJacobJiang** [comment]
谢谢，还真是ignite版本问题，更新后已经通了。还有就是请问跑这个显存大概需要多少呢

**Comment by DJacobJiang** [comment]
> 你安装的ignite和pytorch的版本是否正确？

谢谢，还真是ignite版本问题，更新后已经通了。还有就是请问跑这个显存大概需要多少呢？

**Comment by michuanhaohao** [comment]
1080ti 11G没问题

**Comment by DJacobJiang** [comment]
> 1080ti 11G没问题

好的，谢谢！

**Comment by fenglin218** [comment]
> 你安装的ignite和pytorch的版本是否正确？
遇到同样的问题，torch和ignite的版本都为1.1.0，版本是一样的。

**Comment by ujsyehao** [comment]
@fenglin218 我直接修改代码的 trainer.py 
`checkpointer = ModelCheckpoint(output_dir, cfg.MODEL.NAME, n_saved=10, require_empty=False)`

**Comment by ilovejavav** [comment]
请问怎么升级ignite

**Comment by zzz47zzz** [comment]
See the README.md
3. Install dependencies:
    - [pytorch>=0.4](https://pytorch.org/)
    - torchvision
    - [ignite=0.1.2](https://github.com/pytorch/ignite) (Note: V0.2.0 may result in an error)
    - [yacs](https://github.com/rbgirshick/yacs)

**Comment by Anonymous-DRDL** [comment]
这个要用ignite0.1.2才行，升级过后的ignite1.1不行的

**Comment by Anonymous-DRDL** [comment]
https://github.com/pytorch/ignite/tree/v0.1.2下载，下载好之后本地安装

**Comment by LfieLike** [comment]
if you use anaconda  
try :  conda install -c pytorch ignite=0.1.2

**Comment by lhc11171552** [comment]
> @ fenglin218我直接修改代码的trainer.py
> `checkpointer = ModelCheckpoint(output_dir, cfg.MODEL.NAME, n_saved=10, require_empty=False)`

这样会导致model和optimzer存在一个文件中，并且每跑完一代 都会存储一次

**Comment by lhc11171552** [comment]
> if you use anaconda
> try : conda install -c pytorch ignite=0.1.2

你的方法确实有效果
