### ISSUE TITLE
求全国人工智能大赛(行人重识别)经验分享贴

### ISSUE THREAD

**Issue by Xiangyu-CAS** [michuanhaohao/reid-strong-baseline#136]
首先祝贺大佬在比赛中获得佳绩！想看看和大佬们的差距在哪，不过我暂时未找到任何比赛优胜者的经验分享贴，不知道你是否打算开个贴分享下？

**Comment by michuanhaohao** [comment]
之后过一段时间会把初赛和复赛的方案整理出来，包括代码。决赛有保密协议，所以决赛的不能对外公布。

**Comment by Xiangyu-CAS** [comment]
@michuanhaohao 赞~ 坐等

**Comment by ljd16** [comment]
大佬们可以分享初赛、复赛训练数据集的吗？官网上的链接已经失效了

**Comment by michuanhaohao** [comment]
> 大佬们可以分享初赛、复赛训练数据集的吗？官网上的链接已经失效了

我有是有，但是我不确定能不能发给别人额，这个事情最好还是咨询组委会吧，数据集是公司的，没有开放协议是不能随便传播的

**Comment by michuanhaohao** [comment]
> @michuanhaohao 赞~ 坐等

决赛的答辩PPT组委会做一个推文，复赛初赛可能还要过一段时间，我在准备博士毕业的论文和答辩

**Comment by Xiangyu-CAS** [comment]
@michuanhaohao ，看到知乎推送了[link](https://zhuanlan.zhihu.com/p/109920765)，看到里面提到长尾数据处理，是直接丢弃instance=1的ID吗？在实际工程应用中，会存在大量INSTANCE很少的ID，所以也是直接丢？
