### ISSUE TITLE
cuhk03数据集准确率低的问题

### ISSUE THREAD

**Issue by Lkn1995** [michuanhaohao/reid-strong-baseline#137]
您好，我在cuhk03数据集，跑出来的rank-1只有61%，请问是不是需要调整一些参数，我使用的resnet50作为基准网络，感谢。

**Comment by michuanhaohao** [comment]
我没仔细调过，不过听说好像是的，CUHK03要调整一些参数，包括你也可以试试把triplet放到BN后面，然后用cosine distance

**Comment by Lkn1995** [comment]
好的，谢谢我尝试一下




| |
刘康凝
邮箱：18832696027@163.com
|

签名由 网易邮箱大师 定制

在2020年02月28日 15:49，Hao Luo 写道：

我没仔细调过，不过听说好像是的，CUHK03要调整一些参数，包括你也可以试试把triplet放到BN后面，然后用cosine distance
