### ISSUE TITLE
无监督聚类

### ISSUE THREAD

**Issue by jjn037** [michuanhaohao/reid-strong-baseline#143]
您好 我们最近在做一个竞赛，测试集跟训练集也是跨域，想尝试下您说的无监督聚类方法，我在source domain上训练了模型，用训练好的的模型在target domain上得到特征并使用K-means聚类，发现效果并不好，大多数样本都被分到同一个类里面。请问你们对无监督聚类有什么心得吗？

**Comment by michuanhaohao** [comment]
k-means 挺依赖初始模型的，如果初始模型能够提供比较好的伪标签，模型会越来越好；反之无法提供好的伪标签，模型会越来越差

可以关注我们最近准备放出来的一个工作，《Multi-domain Learning and Identify Mining for Vehicle Re-Identification》，里面有个伪标签的策略我觉得比k-means鲁棒

**Comment by jjn037** [comment]
期待期待
