### ISSUE TITLE
veri.py train on veri776

### ISSUE THREAD

**Issue by ggyybb** [michuanhaohao/reid-strong-baseline#145]
您好，我想问一下，我看到dataset里有支持veri数据集，但是数据集的存放位置和文件夹下的具体格式可以说一下么，就像readme中的market1501，谢谢拉

**Comment by q147258134** [comment]
可以参考data/datasets/veri.py，是按image_train/image_query/image_test放的，我记得文件名和文件夹都是不用改动的。

**Comment by ggyybb** [comment]
> 可以参考data/datasets/veri.py，是按image_train/image_query/image_test放的，我记得文件名和文件夹都是不用改动的。

好的，谢谢，我出现了一个这个问题，您帮我瞅一瞅
![image](https://user-images.githubusercontent.com/61568153/80171720-ae9e3980-861d-11ea-8742-f7100e837053.png)
太感谢了！！

**Comment by q147258134** [comment]
看起来是配置文件的问题，尝试着修改配置参数，好像DATASETS.NAMES和后面的参数中间没有隔开空格，推荐直接在yml里修改参数，每次训练时

**Comment by q147258134** [comment]
看起来是配置文件的问题，尝试修改配置参数看看，好像DATASETS.NAMES和后面的值没有隔开空格。

**Comment by ggyybb** [comment]
> 看起来是配置文件的问题，尝试修改配置参数看看，好像DATASETS.NAMES和后面的值没有隔开空格。

!!!!阿谢谢，就是没加空格，阿，着急犯了低级错误。
