### ISSUE TITLE
运行test.py文件时，在baseline.py文件里load_param总是报错

### ISSUE THREAD

**Issue by Ruzzell13** [michuanhaohao/reid-strong-baseline#148]
使用原代码时会报错像这样
![1](https://user-images.githubusercontent.com/49834250/80684685-9f752b00-8af8-11ea-9f18-3830e8af60d7.png)

参考了#85的疑问之后 改成如下代码仍然报错
![2](https://user-images.githubusercontent.com/49834250/80684714-b025a100-8af8-11ea-920e-3a6c59eb9d9f.png)

当我尝试print相关信息的时候显示是这样
![I5QOOF)V~EU2O I`I0VK__B](https://user-images.githubusercontent.com/49834250/80685122-4fe32f00-8af9-11ea-82c7-512102554a1c.png)

python版本3.6.9
pytorch版本1.2.0
ignite版本0.1.2

**Comment by michuanhaohao** [comment]
你load错模型了，你load的是adam优化器的参数，你load另外一个文件看看

**Comment by Ruzzell13** [comment]
> 你load错模型了，你load的是adam优化器的参数，你load另外一个文件看看

非常感谢，我在载入模型后结果test.py运行结果是这样，请问是正常现象吗？
![TIM图片20200502174314](https://user-images.githubusercontent.com/49834250/80860809-cf5d3380-8c9c-11ea-9dfa-e17966ba6d5d.png)

**Comment by michuanhaohao** [comment]
应该是pytorch版本更新了，稍微有些warning，问题不大
