### ISSUE TITLE
why resnet152 result is poor

### ISSUE THREAD

**Issue by luuuyi** [michuanhaohao/reid-strong-baseline#15]
same as title

**Comment by michuanhaohao** [comment]
Overfitting. The dataset is small-scale and easy. @luuuyi

**Comment by luuuyi** [comment]
@michuanhaohao thanks

**Comment by laihaotao** [comment]
@michuanhaohao Hi, I recently try using ResNet50 and ResNet50v2(pre-activation) as backbone, surprisingly, the v2 performs poorer than v1. Any idea why it happens? Thanks.
