### ISSUE TITLE
您好：请问有提供训练好的模型权重的下载吗？如果有的话是否在“model(Market1501)”这个链接里？里面有好多文件让人困惑。

### ISSUE THREAD

**Issue by finger-monkey** [michuanhaohao/reid-strong-baseline#151]

**Comment by michuanhaohao** [comment]
那是一个模型，但是google上传大文件老断，我就压缩成小包了，你把所有压缩包下下来，然后一起解压就好了

**Comment by laihaotao** [comment]
解压会报错, 还是说需要什么特殊的解压工具？

**Comment by laihaotao** [comment]
我合并了一下上传了一个完整版，直接下载可用，点 [这里](https://drive.google.com/drive/folders/1c2RvIbYOYS75da1BnWwBWBy8LsgGejGz?usp=sharing) 下载。
