### ISSUE TITLE
您的代码测试之后的精度与论文上的最高精度大概差了0.5%，请问最后的这0.5%的精度您是如何提升的？可以介绍一下您的技巧吗？

### ISSUE THREAD

**Issue by finger-monkey** [michuanhaohao/reid-strong-baseline#152]

**Comment by michuanhaohao** [comment]
正常的实验误差，多跑几次。我论文里的结果就是用这份代码跑的，可能不同的pytorch版本和GPU型号会有一点点差异，半个点属于正常的实验误差

**Comment by finger-monkey** [comment]
十分感谢您的回复。可能前几次实验运气比较差没有跑到您论文上的精度。确实是您说的精度误差问题。
在此想再向您咨询另一个问题：请问您论文上的精度market :95.4（94.2）,duke90.3(89.1)，是您实验过程中跑出来的最高精度吗？我们正在试着改进您的基准， 初步跑了几次次实验结果精度比您的论文上的精度提升了0.3%左右-- market：95.7（94.2），我们不确定这是在实验精度误差范围内，还是改进带来的提升，因为您的精度已经很高，很难有明显的提升。当然我们后面还会在duke数据集上做实验。想大概向您了解一下您实验过程中获得的最高精度做一下对比参考。

**Comment by michuanhaohao** [comment]
我只跑了一次，你可以多做几次实验，控制随机种子。如果方法能过比baseline有稳定提升，那就是有效。最高精度差不多就是论文里的，当然如果加上现有的一些新技术可以高一点

**Comment by finger-monkey** [comment]
好的。十分感谢您的回复。我在duke上也做了实验，对比您的论文，map提升了0.3%，rank1提升了0.7%。使用的是很简单的方法进行改进，因为我和您一样追求的是朴实无华的方法。
从您的论文可以看出您追求的是朴实无华方法，学术界很需要学习您的理念。我的理念也是和您一致的。不久前我也曾读过您写过的博客，可以看出您之前的准备比较系统和扎实。我目前还是一个新手，将以您为榜样。
