### ISSUE TITLE
KeyError: 'layer1.0.bn1.running_mean'

### ISSUE THREAD

**Issue by Garish-Green** [michuanhaohao/reid-strong-baseline#153]
I am using resnet50-ibn-a to train and got this error. My config is as follow:
MODEL:
  DEVICE: cuda
  DEVICE_ID: 3,4
  IF_LABELSMOOTH: on
  IF_WITH_CENTER: yes
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: triplet_center
  NAME: resnet50_ibn_a
  NECK: bnneck
  PRETRAIN_CHOICE: imagenet
  PRETRAIN_PATH: /data/wwl/Pretrain/resnet50_ibn_a/resnet50-19c8e357.pth
OUTPUT_DIR: /data/wwl/log/BOT

The path is correct, pretrained model is the same with resnet50.

**Comment by michuanhaohao** [comment]
PRETRAIN_PATH: /data/wwl/Pretrain/resnet50_ibn_a/resnet50-19c8e357.pth

Maybe you load resnet50 model ('resnet50-19c8e357.pth')
