### ISSUE TITLE
Missing parameter “MemorySave” in “re_ranking” function？

### ISSUE THREAD

**Issue by MModerato** [michuanhaohao/reid-strong-baseline#154]
In **reid-strong-baseline/utils/re_ranking.py**, I see the description:
`MemorySave: set to 'True' when using MemorySave mode`

But this parameter setting is not seen in the function re_ranking. 
May I know how to control the memory?

**Comment by michuanhaohao** [comment]
You can refer to this version: https://github.com/heshuting555/NAIC_Person_ReID_DMT/blob/master/utils/reranking.py

**Comment by MModerato** [comment]
Thanks!
