### ISSUE TITLE
Question of the calculation of cosine distance

### ISSUE THREAD

**Issue by serend1p1ty** [michuanhaohao/reid-strong-baseline#155]
Great repo!
But I have a question of the logic of the distance calculation.
I only found the calculation of [Euclidean distance](https://github.com/michuanhaohao/reid-strong-baseline/blob/3da7e6f03164a92e696cb6da059b1cd771b0346d/utils/reid_metric.py#L47).
Where is the calculation of the cosine distance?

**Comment by michuanhaohao** [comment]
If you set 'FEAT_NORM == yes' in the test stage, the ranking result will be same with using cosine distance. (L2 Norm + Euclidean == Cosine distance)
![image](https://user-images.githubusercontent.com/23547900/86019635-6bb37480-ba59-11ea-81c2-39c32d92b6ec.png)

**Comment by serend1p1ty** [comment]
Thank you for your response!
