### ISSUE TITLE
使用训练好的模型重新作为预训练模型

### ISSUE THREAD

**Issue by finger-monkey** [michuanhaohao/reid-strong-baseline#157]
您好，请问假如训练过程当中由于意外而中断，比如总的的训练周期为120，然后我训练到第83周期的时候中断了，想使用第80个周期所生成的模型来继续训练，请问要如何做呢？
以上只是举一个例子，我真正想了解的是，比如说我用您的代码，在A数据集上训练完之后，想利用训练完的模型作为下次训练B数据集模型的预训练模型，请问具体要怎么做呢？
如果直接把imgnet上预训练好的resnet50直接替换掉，会出现以下错误：
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    train(cfg)
  File "tools/train.py", line 30, in train
    model = build_model(cfg, num_classes)
  File "./modeling/__init__.py", line 13, in build_model
    model = Baseline(num_classes, cfg.MODEL.LAST_STRIDE, cfg.MODEL.PRETRAIN_PATH, cfg.MODEL.NECK, cfg.TEST.NECK_FEAT, cfg.MODEL.NAME, cfg.MODEL.PRETRAIN_CHOICE)
  File "./modeling/baseline.py", line 133, in __init__
    self.base.load_param(model_path)
  File "./modeling/backbones/resnet.py", line 137, in load_param
    for i in param_dict:
TypeError: 'Baseline' object is not iterable
期待并感谢您的解答！

**Comment by finger-monkey** [comment]
出于：在A数据集上训练完之后，想利用训练完的模型作为下次训练B数据集模型的预训练模型 的目的，
当我把预训练模型路径改成 MODEL.PRETRAIN_CHOICE == 'self':
我发现您train.py的代码里下面几句会报错。 
# Add for using self trained model 添加使用自训练模型
        if cfg.MODEL.PRETRAIN_CHOICE == 'self':
            start_epoch = eval(cfg.MODEL.PRETRAIN_PATH.split('/')[-1].split('.')[0].split('_')[-1])
            print('Start epoch:', start_epoch)
            path_to_optimizer = cfg.MODEL.PRETRAIN_PATH.replace('model', 'optimizer')
            print('Path to the checkpoint of optimizer:', path_to_optimizer)
            path_to_center_param = cfg.MODEL.PRETRAIN_PATH.replace('model', 'center_param')
            print('Path to the checkpoint of center_param:', path_to_center_param)
            path_to_optimizer_center = cfg.MODEL.PRETRAIN_PATH.replace('model', 'optimizer_center')
            print('Path to the checkpoint of optimizer_center:', path_to_optimizer_center)
            model.load_state_dict(torch.load(cfg.MODEL.PRETRAIN_PATH))
            optimizer.load_state_dict(torch.load(path_to_optimizer))
            center_criterion.load_state_dict(torch.load(path_to_center_param))
            optimizer_center.load_state_dict(torch.load(path_to_optimizer_center))

Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    train(cfg)
  File "tools/train.py", line 89, in train
    model.load_state_dict(torch.load(cfg.MODEL.PRETRAIN_PATH))
  File "/home/GYP/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 818, in load_state_dict
    state_dict = state_dict.copy()
  File "/home/GYP/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'Baseline' object has no attribute 'copy'
想请教您如何解决？ @L1aoXingyu

**Comment by Weiziwei521** [comment]
前面有问题跟这个类似，你可以去看看

**Comment by GJTNB** [comment]
请问你是怎么解决这个问题的，非常感谢

**Comment by finger-monkey** [comment]
抱歉，太久了我想不起来了。这个代码里有的话基本都这是版本问题，好像是保存模型时读取字典的那段代码的新旧版本问题。应该可以在其他问题里找到答案。
