### ISSUE TITLE
Implementation of TripletMarginLoss

### ISSUE THREAD

**Issue by prismformore** [michuanhaohao/reid-strong-baseline#16]
https://github.com/michuanhaohao/reid-strong-baseline/blob/672183d50b11054e24e72306b79692a004bea5cb/layers/triplet_loss.py#L113
 
If I understand it correctly, according to the official guide, [TripletMarginLoss](https://pytorch.org/docs/stable/nn.html?highlight=triplet_margin_loss#torch.nn.functional.triplet_margin_loss) should take (anchor, positive, negative) as forward input instead of (dist_anc_pos, dist_anc_neg, 1).

**Comment by michuanhaohao** [comment]
@prismformore MarginRankingLoss and TripletMarginLoss  are different. TripletMarginLoss also is OK.

**Comment by prismformore** [comment]
You are right. Thank you.
