### ISSUE TITLE
Poor results on the CUHK03 dataset 

### ISSUE THREAD

**Issue by meincv** [michuanhaohao/reid-strong-baseline#160]
Hello,

When I train the model and then use the checkpoints for testing the model, there is no error. However, in the course of training, when it reaches to the epoch 40 and the model wants to be evaluated, I get cuda memory error. 

I changed the batch_size from 64 to 32, then, the first evaluation in epoch 40 was fine, but the evaluation in the epoch 80 ran into the error.

I know that reducing the size of the images or batch size will help not to face with this error, but these solutions are not suitable. Is there any solution to release the cuda memory before entering to the evaluation part?

**Comment by michuanhaohao** [comment]
The cuda memory should be greater that 11G. You can try to use FP16 training.
