### ISSUE TITLE
Loading weights to the Baseline model

### ISSUE THREAD

**Issue by ahrnbom** [michuanhaohao/reid-strong-baseline#161]
My code for now looks as follows:

```
from pathlib import Path

import sys
sys.path.append('reid-strong-baseline')
from modeling.baseline import Baseline

model_path = model_path = Path('reid_files') / 'market_resnet50_model_120_rank1_945.pth'
bl = Baseline(num_classes=1, last_stride=1, model_path=model_path,
                  neck='no', neck_feat='lolwat',
                  model_name='resnet50', pretrain_choice='imagenet')
```
and I downloaded market_resnet50_model_120_rank1_945.pth from your Google Drive link and placed it in a folder called reid_files/. I then expected this to load the model, but I get the following error:

```
Traceback (most recent call last):
  File "lol.py", line 11, in <module>
    model_name='resnet50', pretrain_choice='imagenet')
  File "reid-strong-baseline/modeling/baseline.py", line 132, in __init__
    self.base.load_param(model_path)
  File "reid-strong-baseline/modeling/backbones/resnet.py", line 140, in load_param
    self.state_dict()[i].copy_(param_dict[i])
KeyError: 'base.conv1.weight'
```

To me, the error makes it look like the .pth file doesn't match the network created by the `Baseline` function.

I'm running PyTorch 1.6.0, in case that matters. Is this supposed to work? Am I doing something wrong? I get the same error when using the 'duke' file instead. 

Just to be clear, I only want to load your model, to be able to use it on my own images with my own processing. So I am only interested in loading the `Baseline` model with pretrained weights, which is why I am doing this manually.

**Comment by ahrnbom** [comment]
After carefully studying the code, I figured out the issue. the `pretrain_choice` does not refer to a fully trained model, but only weights for the base network. Therefore, the following code, like, totally works:

```
from pathlib import Path

import sys
sys.path.append('reid-strong-baseline')
from modeling.baseline import Baseline

model_path = model_path = Path('reid_files') / 'market_resnet50_model_120_rank1_945.pth'
bl = Baseline(num_classes=1, last_stride=1, model_path=None,
                  neck='bnneck', neck_feat='lolwat',
                  model_name='resnet50', pretrain_choice='nope')
    
bl.load_param(model_path)
```

Leaving this here in case anyone else wonders the same thing (hi, people from the future!)

Also, in case anyone else struggles to get the spatial maps rather than the vectors after average pooling, you can get them by `bl.base(x)` where `x` is your image.

**Comment by ghost** [comment]
@ahrnbom 
Hi, thanks for the hint.
But I'm getting a weird results when I make a custom inference. I calculated a cosine similarity between two different people an I'm getting ~0.86 while another models shows ~0.047. 

Did you have anything like that ?
