### ISSUE TITLE
Mixup data augmentation with Center loss

### ISSUE THREAD

**Issue by sunilpankaj** [michuanhaohao/reid-strong-baseline#166]
I am able to use mixup with cross entropy loss but not sure how it can be applied with center loss and triplet loss also?
In paper, mixup augmentation is not mentioned. any reason for not using it?

**Comment by michuanhaohao** [comment]
Mix augmentation fuses ID labels of two samples. However, both center loss and triplet loss need to be fed into certain ID labels, so mixup augmentation is not suitable for center loss and triplet loss.

**Comment by JamenceTom** [comment]
Mix augmentation can be applied in triplet loss according to the paper published in icme2021 titled "CUTMIX DUAL BRANCH NETWORK FOR PERSON RE-IDENTIFICATION"
