### ISSUE TITLE
Performance evaluation of resnet50 on market1501 dataset

### ISSUE THREAD

**Issue by InstantWindy** [michuanhaohao/reid-strong-baseline#167]
Hi. I trained the market dataset from scratch and got the following test results: mAP:85.7 rank1:93.9. After reranking, the results were as follows: mAP:93.7 rank1 :95.2.

**Comment by michuanhaohao** [comment]
There may be a little experimental error. I think it is a good performance.

**Comment by InstantWindy** [comment]
But the test results are lower than yours.  Do you train many times and then get the high value on the test dataset? Thanks.
