### ISSUE TITLE
How do I train with my own data set?

### ISSUE THREAD

**Issue by clxa** [michuanhaohao/reid-strong-baseline#169]
Hello, how to use your own data set for training?Your data set has more than 1,501 categories of IDS and only one camera

**Comment by clxa** [comment]
I changed the name of my data set to "Market1501" data set format, but the category is not limited to the category 1501:
=> Market1501 loaded
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    | 19658 |    72824 |         1
  query    |  2458 |     2900 |         1
  gallery  | 11999 |    20465 |         1
  ----------------------------------------
Assert 0 <= PID <= 1501 and then train. But after training, there was no model output. Could you tell me what I did wrong?
Please teach me. Thank you

**Comment by michuanhaohao** [comment]
How many epochs did you train? 

You should not limit the PID between [0,1501]. Please train it as your true IDs.
