### ISSUE TITLE
训练后的模型大小翻了两倍

### ISSUE THREAD

**Issue by mojiayuan** [michuanhaohao/reid-strong-baseline#170]
@L1aoXingyu 您好，r50_ibn_a预训练模型大小90多M,我训练后的模型大小翻了两倍，为什么会这么大的？
![image](https://user-images.githubusercontent.com/54795004/94361727-1f73e100-00e9-11eb-9f93-ab259eea27fa.png)

**Comment by michuanhaohao** [comment]
> ```
> @L1aoXingyu 您好，r50_ibn_a预训练模型大小90多M,我训练后的模型大小翻了两倍，为什么会这么大的？
> ```
> 
> ![image](https://user-images.githubusercontent.com/54795004/94361727-1f73e100-00e9-11eb-9f93-ab259eea27fa.png)

你好，因为的FC层变了，估计你的ID数在几千甚至更大，Backbone的大小是不变的

**Comment by mojiayuan** [comment]
> > ```
> > @L1aoXingyu 您好，r50_ibn_a预训练模型大小90多M,我训练后的模型大小翻了两倍，为什么会这么大的？
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/54795004/94361727-1f73e100-00e9-11eb-9f93-ab259eea27fa.png)
> 
> 你好，因为的FC层变了，估计你的ID数在几千甚至更大，Backbone的大小是不变的哦
哦哦，谢谢答复O(∩_∩)O.
