### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by Alexloveanna** [michuanhaohao/reid-strong-baseline#171]
I' m sorry to trouble you, I meet some question when I test with the model_120.pth,
the error says :TypeError: 'Baseline' object is not iterable

**Comment by unknowone** [comment]
me too

**Comment by furoce** [comment]
me too

**Comment by Alexloveanna** [comment]
I solved by myself ,add"param_dict = param_dict.state_dict()"behind "param_dict = torch.load(trained_path)"in function&nbsp;load_param()




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "michuanhaohao/reid-strong-baseline"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月22日(星期天) 下午2:17
收件人:&nbsp;"michuanhaohao/reid-strong-baseline"<reid-strong-baseline@noreply.github.com&gt;;
抄送:&nbsp;"Mr Loser"<857418074@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [michuanhaohao/reid-strong-baseline] test error (#171)





 
me too
