### ISSUE TITLE
How to train ResNet-34 on person and vehicle ReID datasets like MSMT17 and VeRi?

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [michuanhaohao/reid-strong-baseline#173]
Hi, I want to train ResNet-50 or 34 for person and vehicle on MSMT17 and VeRi dataset.

1- Can I train ResNet for two classes and use both datasets at the same time or I need to train one by one?
2- What is the training process?
2- Can I also use ResNet-18 or ResNet-34 in the same way to increase the speed?

My ultimate goal is to train ResNet ReID model for the person and car. and then combine with this project (https://github.com/GeekAlexis/FastMOT) for Fast multi-object tracking.

How I can achieve this goal?

**Comment by michuanhaohao** [comment]
Please change your config file:

MODEL
      NAME: 'resnet34'

You can train these two datasets at the same time.

**Comment by MuhammadAsadJaved** [comment]
OK. Let me try. Thank you very much. 

@michuanhaohao
