### ISSUE TITLE
train/val split for msmt17 dataset? where to get it.

### ISSUE THREAD

**Issue by boringwar** [michuanhaohao/reid-strong-baseline#174]
Hi, I  do have the MSMT17 dataset, but I dont found the split file in [data/datasets/msmt17.py](https://github.com/michuanhaohao/reid-strong-baseline/blob/3da7e6f03164a92e696cb6da059b1cd771b0346d/data/datasets/msmt17.py#L36), please show me where to get it, thanks.

**Comment by michuanhaohao** [comment]
Please check your dataset files. I consider you lost some files.
