### ISSUE TITLE
RuntimeError:shape '[64,-1'] is invalid for input of size 288

### ISSUE THREAD

**Issue by InstantWindy** [michuanhaohao/reid-strong-baseline#175]
Hi. When I run it, the following error occurred.
![image](https://user-images.githubusercontent.com/23608180/99357863-9fe3e080-28e7-11eb-80a5-668634528f3b.png)

I try to output the value of label.
![image](https://user-images.githubusercontent.com/23608180/99357989-dae61400-28e7-11eb-8f35-19d05cad8c0a.png)

**Comment by michuanhaohao** [comment]
Did you rewrite the code? The current information is too little to locate the problem.

**Comment by InstantWindy** [comment]
Thank you for your reply. I have solved it.  If I change the value of this parameter “IMS_PER_BATCH”, does another parameter “NUM_INSTANCE”need to be changed?

**Comment by michuanhaohao** [comment]
> Thank you for your reply. I have solved it. If I change the value of this parameter “IMS_PER_BATCH”, does another parameter “NUM_INSTANCE”need to be changed?

Right. IMS_PER_BATCH is the number of batch size N. NUM_INSTANCE is the number of IDs P.

**Comment by michuanhaohao** [comment]
K = N/P
