### ISSUE TITLE
how to extract the feature of image after training 

### ISSUE THREAD

**Issue by szh91** [michuanhaohao/reid-strong-baseline#177]
after training, I want to use the trained model to extract the feature of input image

**Comment by michuanhaohao** [comment]
Please refer to [https://github.com/michuanhaohao/reid-strong-baseline/blob/3da7e6f03164a92e696cb6da059b1cd771b0346d/engine/inference.py#L15](https://github.com/michuanhaohao/reid-strong-baseline/blob/3da7e6f03164a92e696cb6da059b1cd771b0346d/engine/inference.py#L15)
