### ISSUE TITLE
请问如何修改三元组采样的P和K？

### ISSUE THREAD

**Issue by GJTNB** [michuanhaohao/reid-strong-baseline#178]
请问想修改batch_size是修改_C.SOLVER.IMS_PER_BATCH 这个参数吗？还有修改三元组采集的P和K是修改哪两个参数？

**Comment by michuanhaohao** [comment]
_C.DATALOADER.NUM_INSTANCE = 16是人数P
_C.SOLVER.IMS_PER_BATCH是BS

K = BS/P会自动计算
