### ISSUE TITLE
SeResNet50 as backbone

### ISSUE THREAD

**Issue by Lin-UH** [michuanhaohao/reid-strong-baseline#185]
Hello, I have a question about using SeResNet50 as backbone, it seems like torch doesn't provide pre-trained SeResNet50 and I can't find one online. 

from defaults.py 
# Options: 'imagenet' or 'self'
_C.MODEL.PRETRAIN_CHOICE = 'imagenet'

I can only choose 'imagenet' or 'self', but I don't have them either. 
In this situation, how should I set  this _C.MODEL.PRETRAIN_PATH value?  What I need to do if I simply want to start training with random initialization?

**Comment by Lin-UH** [comment]
I just find the model  from here
https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/senet.py

Another question is if I want to only save the backbone model after training the model, what should I do?, is there a interface for this?

**Comment by michuanhaohao** [comment]
I consider you can delete all 'torch.load' and 'load_param' in your setting.

**Comment by Lin-UH** [comment]
Thank you very much
