### ISSUE TITLE
MSMT17 configs

### ISSUE THREAD

**Issue by WongChen** [michuanhaohao/reid-strong-baseline#186]
Is there a recommended configs for msmt17 dataset, since I found simplely replace the dataset dir in softmax_triplet_with_center.yml with msmt17 doesn't work well (very low mAP / R1).  Are there any specific settings for this dataset?

**Comment by michuanhaohao** [comment]
Yes, we did not focus on the training on MSMT17. The training settings for MSMT should be changed. You can refer to fast-reid https://github.com/JDAI-CV/fast-reid/tree/master/configs/MSMT17
