### ISSUE TITLE
测试cuhk03有问题

### ISSUE THREAD

**Issue by Mr-Da-Yang** [michuanhaohao/reid-strong-baseline#187]
作者你好：
1. 我在cuhk03（detected，no_split,no_metric）上进行测试[40,70]学习率下（rank1-61.6，map-59.7）
[80,160]学习率下（68.2，67.1）发现这个基线指标有些低，这个正常吗，其他人也有这样问题吗？
2. 在您的教学课件里，有个专门给cuhk03用的度量法，用了以后发现map>rank1,请问我要用这个度量法吗，在其他论文中，没发现map>rank的现象。
期待你的答复！！

**Comment by CQUcheng** [comment]
请问下，使用[80,160]学习率下在cuhk03 labeled数据集测试结果是怎样的

**Comment by Mr-Da-Yang** [comment]
教学中的cuhk03的度量方法是针对划分后的cuhk03数据集使用的，这点我现在才发现，所以用

market度量方法直接度量cuhk即可。
对于这cuhk03数据集，lr影响很大，我调的最好的参数是：基础学习率=0.00045，[45,180],迭代
300次，cuhk03 labeled（74.4，72.7），你测试结果可以分享下吗

**Comment by Mr-Da-Yang** [comment]
> 请问下，使用[80,160]学习率下在cuhk03 labeled数据集测试结果是怎样的
对于这cuhk03数据集，lr影响很大，我调的最好的参数是：基础学习率=0.00045，[45,180],迭代
300次，cuhk03 labeled（74.4，72.7），你测试结果可以分享下吗

**Comment by CQUcheng** [comment]
我现在用的作者论文里的学习率，发现结果不尽人意，尝试你推荐的发现效果提升不少，目前还在调整参数，达到最优再回复下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "michuanhaohao/reid-strong-baseline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [michuanhaohao/reid-strong-baseline] 测试cuhk03有问题 (#187)





  
请问下，使用[80,160]学习率下在cuhk03 labeled数据集测试结果是怎样的
 对于这cuhk03数据集，lr影响很大，我调的最好的参数是：基础学习率=0.00045，[45,180],迭代
 300次，cuhk03 labeled（74.4，72.7），你测试结果可以分享下吗

**Comment by CQUcheng** [comment]
目前我也在调整参数，有进展会回复下
