### ISSUE TITLE
UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`

### ISSUE THREAD

**Issue by MuadDev** [michuanhaohao/reid-strong-baseline#190]
Starting training gives me the following warning:
```
/opt/conda/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:100: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate          "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
```
I have pytorch 1.3.1 installed.

Should I be worried about this?

**Comment by MuadDev** [comment]
Perhaps file "trainer.py" should change this:
```
    @trainer.on(Events.EPOCH_STARTED)
    def adjust_learning_rate(engine):
        scheduler.step()
```
to this:
```
    @trainer.on(Events.EPOCH_COMPLETED)
    def adjust_learning_rate(engine):
        scheduler.step()
```
Or not?

**Comment by michuanhaohao** [comment]
> Perhaps file "trainer.py" should change this:
> 
> ```
>     @trainer.on(Events.EPOCH_STARTED)
>     def adjust_learning_rate(engine):
>         scheduler.step()
> ```
> 
> to this:
> 
> ```
>     @trainer.on(Events.EPOCH_COMPLETED)
>     def adjust_learning_rate(engine):
>         scheduler.step()
> ```
> 
> Or not?

You are right. New versions of Pytorch result in such warning. But it does not influence the performance a lot.
