### ISSUE TITLE
RandomIdentitySampler

### ISSUE THREAD

**Issue by onlinehuazai** [michuanhaohao/reid-strong-baseline#193]
报错,  pop()  请问有人遇到这个问题吗

**Comment by onlinehuazai** [comment]
batch_idxs = batch_idxs_dict[pid].pop(0)
IndexError: pop from empty list

**Comment by michuanhaohao** [comment]
你检查下你的dataset，是不是一个空list，看上去你的数据集路径可能有问题，没有读到图片
