### ISSUE TITLE
训练cuhk03数据集报错

### ISSUE THREAD

**Issue by LY-cmd-xtt** [michuanhaohao/reid-strong-baseline#196]
@michuanhaohao 
大神你好，我现在使用Python3.6、pytorch1.8.1、torchvision0.9.1、cudatoolkit11.1 ，其他配置文件都与您readme中所述的一致。我在该环境下成功训练和测试了market1501、dukemtmc-reid两个数据集，但是在训练cuhk03数据集时报错OSError: ./data/cuhk03/images_detected/2_309_1_03.png does not exist。我换了您deep-person-reid-master的代码跑这个数据集也是提示这样的错误。并且如果我重新在run一次，报错时显示的图片会发生变化，如：变成了OSError: ./data/cuhk03/images_detected/1_819_1_02.png does not exist。但是这些图片都可以在images_detected文件夹中找到，softmax_triplet_with_center.yml和cuhk03.py文件中的数据集路径我检查过多次，并没有发现问题。难道是softmax_triplet_with_center.yml文件中的其他参数还需要更改吗？

**Comment by michuanhaohao** [comment]
你改成绝对路径看一下，有时候相对路径容易出问题

**Comment by LY-cmd-xtt** [comment]
@michuanhaohao 
感谢您在百忙之中抽出时间帮我解答疑惑。
但是我还是存在困惑。因为我一直都是在defaults.py和cuhk03.py文件中导入数据集的绝对路径。我需要在您的源代码导入图片路径部分（ img_paths）做出修改吗？我在网上查找了很多关于将相对路径改成绝对路径的方法，发现都没有用。请问具体代码部分应该如何进行修改呢？期待您的答复。

**Comment by michuanhaohao** [comment]
> @michuanhaohao
> 感谢您在百忙之中抽出时间帮我解答疑惑。
> 但是我还是存在困惑。因为我一直都是在defaults.py和cuhk03.py文件中导入数据集的绝对路径。我需要在您的源代码导入图片路径部分（ img_paths）做出修改吗？我在网上查找了很多关于将相对路径改成绝对路径的方法，发现都没有用。请问具体代码部分应该如何进行修改呢？期待您的答复。

不需要，你把config里面的data root路径改一下就好了

**Comment by LY-cmd-xtt** [comment]
@michuanhaohao 
谢谢您的指点，不过我config中DATASETS.ROOT_DIR = ('/home/liuyue/下载/reid-strong-baseline-master/data')用的是绝对路径。我最后是在dataset_loader.py中最后读图片前加
img_path = img_path.strip(".")
 img_path = "/home/liuyue/下载/reid-strong-baseline-master" + img_path
这两行代码解决了问题。

**Comment by michuanhaohao** [comment]
> @michuanhaohao
> 谢谢您的指点，不过我config中DATASETS.ROOT_DIR = ('/home/liuyue/下载/reid-strong-baseline-master/data')用的是绝对路径。我最后是在dataset_loader.py中最后读图片前加
> img_path = img_path.strip(".")
> img_path = "/home/liuyue/下载/reid-strong-baseline-master" + img_path
> 这两行代码解决了问题。

ok
