### ISSUE TITLE
Good job !

### ISSUE THREAD

**Issue by Qidian213** [michuanhaohao/reid-strong-baseline#2]
恭喜罗浩大神又取得新的成果，我简单看了下你们的论文，像是对目前的方法做了一些思考并改进提升，却以非常简单的模型结构取得了很好的效果。 在不同的损失函数学习的特征空间分布特征部分，我在前两天看到 https://arxiv.org/abs/1903.03238 这篇论文也有些相似的思考，不知道你们是否也做过相关的研究？ 后续我会尝试将你们结合一下，做些测试。

**Comment by michuanhaohao** [comment]
@Qidian213 谢谢你的评价和建议。ranking list loss这个其实在深度学习出来以前就有类似思想的工作。N pair也好，rank loss也好，在人脸以及图像检索这几个数据集上都取得了挺好的效果，但是在reid数据集上效果一直一般，调参还没调好。我的观点差不多就是论文里面表达的，度量学习是欧式空间的距离，表征学习是分类空间的余弦距离，这两种类型的约束不能同时针对于一个feature，但是呢就是一直无法得到统一的结论，可能换个情形这个观点就不成立了。这篇文章我看过，但是没有复现过也没做过研究，有什么结果的话也欢迎分享。

**Comment by xiaoweihappy123** [comment]
前几天刚看完李沐大佬对于图像分类的bag of tricks想用到Reid中试一下，今天就看到罗大神的总结了。缘妙不可言

**Comment by michuanhaohao** [comment]
@xiaoweihappy123 然而李沐大佬的中了CVPR，我的仅仅是做个tech report开源出来
