### ISSUE TITLE
reproducibility of with-center-loss on market

### ISSUE THREAD

**Issue by zhch-sun** [michuanhaohao/reid-strong-baseline#21]
Hi, thank you for the awesome work!
I reproduce the Experiment-all_tricks-softmax-market twice, and both achieve 94.1 top1 acc. 
should this be 94.5?

**Comment by michuanhaohao** [comment]
@zhch-sun Different machines/GPUs may achieve different performance. We have found that some machines achieved better performance while others  achieved worse performance. 0.4% is not a large gap. How about the performance without center loss is?

**Comment by zhch-sun** [comment]
The performance without center loss is 94.1, just as paper said. 
And when I test with reranking, with-center-loss on market achieves map and rank1 on par with the paper
~ FYI

**Comment by zhch-sun** [comment]
I guess you may just close this issue, thanks for your reply
