### ISSUE TITLE
如何在imagenet上做预训练

### ISSUE THREAD

**Issue by wangsiling59** [michuanhaohao/reid-strong-baseline#211]
作者您好，感谢您的精彩分享。有一个问题想请教一下，您是如何在imagenet上做预训练的，关于模型的输入部分，crop和resize您是怎么做的呢，大小分别是多少呢，期待您的回复！

**Comment by michuanhaohao** [comment]
ImageNet预训练需要参考ImageNet的训练呢：https://github.com/rwightman/pytorch-image-models
