### ISSUE TITLE
training way of domain adaptation

### ISSUE THREAD

**Issue by SWRDFK** [michuanhaohao/reid-strong-baseline#24]
Hi, author, thank you for your excellent work! I would like to know how can I employ this baseline for domain adaptive person re-id. In other words, what's the way of network training for cross domain and what's the difference with direct transfer (models trained on source domain are tested on target domain)?

**Comment by michuanhaohao** [comment]
You can train and test the model with different datasets. For example:

Train:
```
DATASETS:
  NAMES: ('market1501')
```

Test (Load the model trained on Market):
```
DATASETS:
  NAMES: ('dukemtmc')
TEST.WEIGHT:
  ('your path to trained checkpoints')
```

You also can modified the config file for more convenience.

**Comment by 2110317008** [comment]
> You can train and test the model with different datasets. For example:
> 
> Train:
> 
> ```
> DATASETS:
>   NAMES: ('market1501')
> ```
> 
> Test (Load the model trained on Market):
> 
> ```
> DATASETS:
>   NAMES: ('dukemtmc')
> TEST.WEIGHT:
>   ('your path to trained checkpoints')
> ```
> 
> You also can modified the config file for more convenience.



Can you explain in detail how to modify the config file to achieve training on the B dataset on the A dataset?
