### ISSUE TITLE
Can you open source code for the following methods in table4?

### ISSUE THREAD

**Issue by jianwu585218** [michuanhaohao/reid-strong-baseline#25]
![image](https://user-images.githubusercontent.com/34296200/57203465-dfd3c300-6fe2-11e9-925c-782e2e6cd069.png)
I want to try the excellent model in the picture above, but I can't find open source code. Can you open source?
Thanks.

**Comment by michuanhaohao** [comment]
@jianwu585218 All results were reported in their papers. We did not reproduce them.
