### ISSUE TITLE
出现RuntimeError: DataLoader worker (pid(s) 15927) exited unexpectedly的问题

### ISSUE THREAD

**Issue by Deeplearning20** [michuanhaohao/reid-strong-baseline#29]
您好，我遇到了raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 15927) exited unexpectedly的问题，我该怎样解决这个问题啊？谢谢您
![1557319522(1)](https://user-images.githubusercontent.com/39185624/57376526-cb561d00-71d2-11e9-8a09-a7cc65402cbc.png)

**Comment by Deeplearning20** [comment]
@michuanhaohao 把DataProvider的num_workers改为0，管用了，谢谢您

**Comment by 106224** [comment]
I have solved this problem.
