### ISSUE TITLE
python 2 compatibility 

### ISSUE THREAD

**Issue by Oewyn** [michuanhaohao/reid-strong-baseline#3]
Was the codebase originally intended to be run on python2 or python 3?

I'm running into an issue with the urllib module.

in python2 urlretrieve is located at `url.urlretrieve`
in python3 urlretrieve is located at `url.request.urlretrieve`

from `data/datasets/dukemtmcreid.py` it seems that the download code was written assuming python2 but a lot of other things are pointing to assuming a python3 install (e.g.) engine folder doesn't have `__init__.py` therefore tools/train.py cannot successfully execute the following line on python 2:
   
    from engine.trainer import do_train, do_train_with_center

I think I have a pull request or two I would like to make, but don't know how to proceed until it's clear whether this project is supposed to support both python2 and python3, or only python3 support is desired.

**Comment by L1aoXingyu** [comment]
Hi, only python3 is supported for this project, and we have already fixed this problem. Feel free to raise issues if you have any questions.
