### ISSUE TITLE
Continue training after an accident

### ISSUE THREAD

**Issue by h-bo** [michuanhaohao/reid-strong-baseline#30]
Is there a simple way to continue training after an accident?

**Comment by shaoniangu** [comment]
If there are model checkpoints saved, your can restore it to continue your training process. The detailed procedure are listed in README. Model checkpoints are saved per 40 epoch as default. You can change this configuration according to your demand.

**Comment by shaoniangu** [comment]
If there are model checkpoints saved, your can restore it to continue your training process. The detailed procedures are listed in README. Model checkpoints are saved per 40 epoch as default. You can change this configuration according to your demand.

**Comment by h-bo** [comment]
You mean, By loading a pretrained model style ?

**Comment by shaoniangu** [comment]
Yes. Can this solve your problem?

**Comment by h-bo** [comment]
This is a solution, but I wonder if the momentum used in adam saved. If not, tiny lr problem will occur

**Comment by shaoniangu** [comment]
The model parameters and the optimizer parameters are all saved. In my experiments, there is no difference.  I did not conduct lots of experiments in this aspect, you may take a try to prove it.

**Comment by shaoniangu** [comment]
The model parameters and the optimizer parameters are all saved. In my experiments, there is no difference. You may take a try to prove it.

**Comment by h-bo** [comment]
I mis-read （3）Load your self-trained model
It works well for me
Thanks sincerely~

**Comment by shaoniangu** [comment]
My pleasure~
