### ISSUE TITLE
warm up trick

### ISSUE THREAD

**Issue by xiaoweihappy123** [michuanhaohao/reid-strong-baseline#31]
你好，我有个疑问，论文中的学习率前十轮使用warm up，公式：3.5x10^-5 x t/10，当t=1时学习率为3.5x10^-6，当t=10的时候为学习率3.5x10^-5，然后再突然增大十倍到3.5x10^-4？
感觉和图片所示的逐步增大的效果有出入？
初始warm up的学习率为什么要降低10倍？
因为我理解的warm up公式应该是：lr x t/10，这样的话学习率才慢慢的增大到lr。
希望能解答我的疑惑。

**Comment by michuanhaohao** [comment]
@xiaoweihappy123 这是一个小笔误，公式（1）应该改为3.5×10^-4×t/10， 看图的话会好明白一些，就是一个正常的线性warmup，感谢提醒
