### ISSUE TITLE
no module named 'utils.iotools'

### ISSUE THREAD

**Issue by wujunyi627** [michuanhaohao/reid-strong-baseline#32]
我下载了整个文章的代码工程，但是用sh  ***.sh  会出现no module named 'utils.iotools' 的 错误。

**Comment by michuanhaohao** [comment]
@wujunyi627 你在根目录运行一下，如果还报错就是python环境和路径的问题，utils.iotools文件是存在的

**Comment by hyzl-4869** [comment]
你好，请问你这个问题解决了吗
