### ISSUE TITLE
cosine and  euclidean?

### ISSUE THREAD

**Issue by lwplw** [michuanhaohao/reid-strong-baseline#33]
Hi, thank your for your work.In your scripts, when calculate accuracy after feature extraction, Do these two parameters TEST.FEAT_NORM "('yes')" and NECK_FEAT: after determine the final distance calculation method?  
I'm so confused that where is the distance calculation of cosine dis and euclidean ？ 
waitting for ur reply！ Thank you！

**Comment by shaoniangu** [comment]
Hi, the parameters TEST.FEAT_NORM "('yes')" and NECK_FEAT: after  do determine the distance calculation in evaluation and testing periods. NECK_FEAT determines which feature (before or after BNNeck) is used for testing. And the parameter FEAT_NORM determines whether the feature is normalized for testing. If FEAT_NORM=‘yes’, the feature will be normalized and the distance calculation of normalized feature is equivalent to cosine distance.  And if FEAT_NORM=‘no’, the feature will not be normalized and the distance calculation is euclidean distance.

**Comment by lulujianjie** [comment]
Hi, I added cosine computation in my forked repository [link](https://github.com/lulujianjie/person-reid-tiny-baseline). hope it helpful for you.

**Comment by lwplw** [comment]
@lulujianjie Thank you very much, I can't find where the cosine computation was implemented in the original repo code.

**Comment by lulujianjie** [comment]
> @lulujianjie Thank you very much, I can't find where the cosine computation was implemented in the original repo code.

see [link](https://github.com/lulujianjie/person-reid-tiny-baseline/blob/master/utils/metrics.py)
