### ISSUE TITLE
关于数据增强

### ISSUE THREAD

**Issue by luuuyi** [michuanhaohao/reid-strong-baseline#36]
你好，请问一下在数据增强部分的实验中，你们有试过mixup这个操作么。

**Comment by michuanhaohao** [comment]
@luuuyi 没有呢，主要是mixup之后ID label不知道怎么确定，如果有好的实验结果，欢迎分享一下

**Comment by luuuyi** [comment]
@michuanhaohao 好的

**Comment by JamenceTom** [comment]
mixup可以使用了，在icme2021的论文“CUTMIX DUAL BRANCH NETWORK FOR PERSON RE-IDENTIFICATION”中提出样本经过mixup或者cutmix之后，得到插值后的样本特征，同时保持原始样本特征。在做triplet loss计算的时候，d_ap等于anchor（混合了两个类特征）到两个类的距离的插值，d_an计算方式不变
