### ISSUE TITLE
使用Fi计算Triplet loss 实验。

### ISSUE THREAD

**Issue by Qidian213** [michuanhaohao/reid-strong-baseline#37]
昨天突然想到用 Fi 计算Triplet loss , 只不过损失函数为 xent + 0.2 triplet . 其余均未做任何改动。
在DukeMTMC-REID数据集上得到
```
mAP = 75.8%
Rank-1 = 86.8 %
```
 似乎可以得到与论文中（未加center loss）相似的数据甚至还好一点点，而且只使用了 0.2triplet loss做实验，实验不同的比重有可能得到更好的结果。

**Comment by michuanhaohao** [comment]
@Qidian213 我们做过了这个实验，用fi同时算ID和triplet loss，保持所以参数不变，最终结果是收敛不好

**Comment by Qidian213** [comment]
那么神奇。
