### ISSUE TITLE
How to simplify this code as a baseline?

### ISSUE THREAD

**Issue by SWRDFK** [michuanhaohao/reid-strong-baseline#39]
Thanks for your excellent work! I found there are so many files and configures, what should I do if I want to use the code with best performance as my baseline? Could you provide a simple version?

**Comment by michuanhaohao** [comment]
There is a good project. [link](https://github.com/wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks)

**Comment by SWRDFK** [comment]
Thank you so much! That's just what I need.
