### ISSUE TITLE
Resnet lacks the first relu layer

### ISSUE THREAD

**Issue by Gary-Deeplearning** [michuanhaohao/reid-strong-baseline#4]
Hi, Dr.Luo. 
I found that your resnet **lacks the first relu layer** compared with normal resnet50. I don't know whether this is your fault or a trick. Then I added relu layer and I have trained the model twice with the image size is 256*128, and the results are as follows:
**Rank1: 94.65%, the mAP: 86.15%
Rank1: 94.47%, the mAP: 86.27%**
I think there may be some random errors here, but the mAP I got is higher than the original version.

**Comment by michuanhaohao** [comment]
@Gary-Deeplearning Thanks for your kind reminder! It is a mistake. We will repair it in the future.

But it seems have not too much influence on the performance.

**Comment by Gary-Deeplearning** [comment]
@michuanhaohao Yep, Because of the capacity of the NN, maybe one relu layer is not likely to affect performance.
