### ISSUE TITLE
The distance matrix

### ISSUE THREAD

**Issue by ericsqxd** [michuanhaohao/reid-strong-baseline#40]
In the inference stage, I'm not clear about the distance matrix.
`distmat = torch.pow(qf, 2).sum(dim=1, keepdim=True).expand(m, n) + \
                  torch.pow(gf, 2).sum(dim=1, keepdim=True).expand(n, m).t()`
What's the purpose of the code? Could you solve my confusion?Thank you!

**Comment by michuanhaohao** [comment]
@ericsqxd Using tensors to computer L2 distance.
