### ISSUE TITLE
Have you tried other Hard Data Mining Strategy?

### ISSUE THREAD

**Issue by jerryhitit** [michuanhaohao/reid-strong-baseline#41]
In this repo, Batch-Hard method was used to construct a DataLoader. And in DukeMTMCT repo DeepCC(while the official code is not accessible by now and many fork repos still can be found), it claims that another Batch-Weighted and Batch-Sample outpreforms Batch-Hard method. In your experiments, have you ever tried other hard data mining methods and tested thier performance?

**Comment by michuanhaohao** [comment]
@jerryhitit I have not tried in this repo. I tried it in other repo. My conclusion is that it is hard to assess which one is better. These two losses achieve similar performance.
