### ISSUE TITLE
A tiny reid baseline 

### ISSUE THREAD

**Issue by lulujianjie** [michuanhaohao/reid-strong-baseline#42]
Hi, this is a really nice project! I reconstructed it by referring your code and create a tiny reid baseline [link](https://github.com/lulujianjie/person-reid-tiny-baseline), which 
- does not need to install ignite and yacs
- supports computing DistMap using cosine similarity
- sets hyperparameters using a configuration class
I also added your paper's BibTeX in README. For other requirements, please feel free to contact me.

**Comment by michuanhaohao** [comment]
Thank you vary much! I will add it into our project.
