### ISSUE TITLE
About warming-up lr scheduler

### ISSUE THREAD

**Issue by silverbulletmdc** [michuanhaohao/reid-strong-baseline#44]
Hi Hao Luo.
This is a very nice baseline project for reid.
I read the source code and found that the `WarmupMultiStepLR` does not correspond to your paper. 
In your paper, you write that:
![image](https://user-images.githubusercontent.com/11981375/59663018-b660a680-91e0-11e9-987d-412705b9f2dc.png)
There is a mistake that the first row of the equation should be `3.5*1e-4*t/10`. Anyway, that doesn't matter. But in your code, I found the algorithm you use equals to `3.5*1e-4*(t/10+0.01*(1-t/10)`, which can be simplified to `0.01+0.99*t/10`
Is this a mistake or some trick you didn't mention in your paper?

**Comment by michuanhaohao** [comment]
Yes. Thank you! I also found this mistake and will correct it in updated version.
