### ISSUE TITLE
已经训练好的模型

### ISSUE THREAD

**Issue by ShiJing123** [michuanhaohao/reid-strong-baseline#48]
您好，哪里可以获取到已经训练好的模型，可以直接进行测试的，谢谢。

**Comment by michuanhaohao** [comment]
Readme里面有个模型下载链接，稍微仔细的读一下，能找到的

**Comment by ShiJing123** [comment]
嗯嗯，已经找到了，谢谢。

**Comment by jhxing** [comment]
> 嗯嗯，已经找到了，谢谢。

Hi 您好，我也找到了模型的下载链接，但是是类似于 ”zip.45“ 这样的格式， 我解压缩每次都失败，所以想问下你是怎么处理的？

**Comment by ShiJing123** [comment]
全部下载下来，解压第一个文件


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: jhxing <notifications@github.com>
发送时间: 2019年7月11日 12:02
收件人: michuanhaohao/reid-strong-baseline <reid-strong-baseline@noreply.github.com>
抄送: ShiJing123 <774231254@qq.com>, Author <author@noreply.github.com>
主题: 回复：[michuanhaohao/reid-strong-baseline] 已经训练好的模型 (#48)



 
嗯嗯，已经找到了，谢谢。
  
Hi 您好，我也找到了模型的下载链接，但是是类似于 ”zip.45“ 这样的格式， 我解压缩每次都失败，所以想问下你是怎么处理的？

**Comment by jhxing** [comment]
> 全部下载下来，解压第一个文件 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: jhxing <notifications@github.com> 发送时间: 2019年7月11日 12:02 收件人: michuanhaohao/reid-strong-baseline <reid-strong-baseline@noreply.github.com> 抄送: ShiJing123 <774231254@qq.com>, Author <author@noreply.github.com> 主题: 回复：[michuanhaohao/reid-strong-baseline] 已经训练好的模型 (#48) 嗯嗯，已经找到了，谢谢。 Hi 您好，我也找到了模型的下载链接，但是是类似于 ”zip.45“ 这样的格式， 我解压缩每次都失败，所以想问下你是怎么处理的？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

好的，多谢，我去试一下

**Comment by laihaotao** [comment]
我合并了一下上传了一个完整版，直接下载可用，点 [这里](https://drive.google.com/drive/folders/1c2RvIbYOYS75da1BnWwBWBy8LsgGejGz?usp=sharing) 下载。
