### ISSUE TITLE
Update to ignite 0.2.0

### ISSUE THREAD

**Issue by vfdev-5** [michuanhaohao/reid-strong-baseline#49]
Do you plan to update the code up to ignite 0.2.0 ?

Most probably, the only change is to replace the objects passed to `ModelCheckpoint` : 
- https://github.com/michuanhaohao/reid-strong-baseline/blob/master/engine/trainer.py#L159
- https://github.com/michuanhaohao/reid-strong-baseline/blob/master/engine/trainer.py#L238

Reference: 
- https://github.com/pytorch/ignite/issues/529

**Comment by michuanhaohao** [comment]
Thank you very much. If you have test these codes, you can commit a PR and become a contributor of this project.
