### ISSUE TITLE
Potential typo? super().__init__()

### ISSUE THREAD

**Issue by priyankclarifai** [michuanhaohao/reid-strong-baseline#50]
In this code : 
https://github.com/michuanhaohao/reid-strong-baseline/blob/master/modeling/backbones/resnet.py#L93

**super().__init__()** should be replaced by **super(ResNet, self).__init__()**

**Comment by michuanhaohao** [comment]
Thank you very much. Did you encounter a bug with 'super().init()'?

**Comment by priyankclarifai** [comment]
yes, I guess super keyword doesn't work without class name

**Comment by michuanhaohao** [comment]
Python2 or Python3? We have not encountered it yet.

**Comment by priyankclarifai** [comment]
Oh I'm using python2

**Comment by michuanhaohao** [comment]
We recommend using Python3. 

This is another repo implemented by Python2.
[https://github.com/wangguanan/Pytorch-Person-REID-Baseline-Bag-of-Tricks](url)
