### ISSUE TITLE
Failed to use softmarginloss

### ISSUE THREAD

**Issue by John-Yao** [michuanhaohao/reid-strong-baseline#58]
I tried to user softmarginloss by set SOLVER:MARGIN:None in config file. It report the type err by yacs:
ValueError: Type mismatch (<class 'float'> vs. <class 'str'>) with values (0.3 vs. None) for config key: SOLVER.MARGIN
Now I using softmarginloss by modify the make_loss function.

**Comment by michuanhaohao** [comment]
I remember there is not softmarginloss in our project?

**Comment by John-Yao** [comment]
The softmarginloss  is used in the ranking loss of class TripletLoss（triplet_loss.py）.

**Comment by michuanhaohao** [comment]
OK, I got it. We have never encountered this problem.

**Comment by shaoniangu** [comment]
I think this problem is caused by the data type mismatch when merging the command line or yml file with the default settings. The data type in default.py of SOLVER.MARGIN is float, but the setting of SOLVER.MARGIN is None in your setting.

**Comment by John-Yao** [comment]
@shaoniangu Yeah, Is there another elegant way to pass None from config file to defaut settings?

**Comment by shaoniangu** [comment]
The data type must be same, so you can directly change SOLVER.MARGIN to None in defaults.py.

**Comment by John-Yao** [comment]
@shaoniangu Thanks
