### ISSUE TITLE
single image test

### ISSUE THREAD

**Issue by wait1988** [michuanhaohao/reid-strong-baseline#6]
I wrote a test demo following the code in test.py:

    transform = T.Compose([
            T.Resize(cfg.INPUT.SIZE_TEST),
            T.ToTensor(),
            T.Normalize(mean=cfg.INPUT.PIXEL_MEAN, std=cfg.INPUT.PIXEL_STD)
        ])

    device = cfg.MODEL.DEVICE
    num_classes = 751 
    model = build_model(cfg, num_classes)
    model.load_param(cfg.TEST.WEIGHT)
    model.to(device)
    model.eval()
    img_path="~/dataset/market1501/query/1061_c2s2_138552_00.jpg"
    img = Image.open(img_path).convert('RGB')
    data = transform(img)
    with torch.no_grad():
         data = data.cuda()
         feat = model(data)
And got the following error:
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 3-dimensional input of size [3, 384, 128] instead
Anyone knows how to fix it?

**Comment by L1aoXingyu** [comment]
```
data = transform(img)
data = data.unsqueeze(0)
with torch.no_grad():
...
```
The data size is [3, 384, 128] and the network needs a input with [batch_size, 3, 384, 128], so you should add an additional axis.

**Comment by wait1988** [comment]
Thanks so much.

**Comment by junxiaoge** [comment]
@wait1988 The test examples I showed are all about testing the entire data set. Now I need to test with a single picture. What should I do?
