### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by LilySys** [michuanhaohao/reid-strong-baseline#61]
本人小白，希望大佬能指点。
配置文件中CHECKPOINT_PERIOD: 40  LOG_PERIOD: 20 EVAL_PERIOD: 40，请问到epoch为40时，为什么会报这个错ValueError: Object should have `state_dict` method？

**Comment by michuanhaohao** [comment]
pytorch的版本，python的版本，以及运行的命令行提供一下

**Comment by 15338981081** [comment]
engine/trainer.py
#trainer.add_event_handler(Events.EPOCH_COMPLETED, checkpointer, {'model': model.state_dict(), # 'optimizer': optimizer.state_dict()}) trainer.add_event_handler(Events.EPOCH_COMPLETED, checkpointer, {'model': model, 'optimizer': optimizer})

**Comment by 15338981081** [comment]
网上有人提供了这样的解决方案，会对程序有什么影响呢？

**Comment by michuanhaohao** [comment]
大概知道了，CPU和GPU直接有时候会差一个modules，model.modules.state_dict()，你断点调试一下看看

**Comment by LilySys** [comment]
pytorch版本1.0.1.post     python版本：3.6.5    
我配置的vscode，vscode的lauch.json配置如下：
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "cwd":"/home/wl/.pytorch_project/person_reid/reid-strong-baseline",
            "args":["--config_file","configs/softmax_triplet.yml",
                     "MODEL.DEVICE_ID","3",
                     "DATASETS.NAMES","market1501",
                     "DATASETS.ROOT_DIR","/home/wl/.pytorch_project/person_reid/reid-strong-baseline/data",
                     "OUTPUT_DIR","/home/wl/.pytorch_project/person_reid/reid-strong-baseline/log/Experiment-all_tricks-without_center-market"]        
        }
    ]

**Comment by LilySys** [comment]
> engine/trainer.py
> #trainer.add_event_handler(Events.EPOCH_COMPLETED, checkpointer, {'model': model.state_dict(), # 'optimizer': optimizer.state_dict()}) trainer.add_event_handler(Events.EPOCH_COMPLETED, checkpointer, {'model': model, 'optimizer': optimizer})

大佬，你的意思是注释#trainer.add_event_handler这个函数？

**Comment by 15338981081** [comment]
https://github.com/pytorch/ignite/issues/529
这里说貌似删了.state_dict()就好了，但我不知道会不会对程序造成影响

**Comment by LilySys** [comment]
> [pytorch/ignite#529](https://github.com/pytorch/ignite/issues/529)
> 这里说貌似删了.state_dict()就好了，但我不知道会不会对程序造成影响

非常感谢，可以了。

**Comment by michuanhaohao** [comment]
@15338981081 感谢

**Comment by michuanhaohao** [comment]
@LilySys 应该ignite版本问题
