### ISSUE TITLE
Is there a SEResNet50 baseline result for comparsion?

### ISSUE THREAD

**Issue by MasterofPLM** [michuanhaohao/reid-strong-baseline#66]

**Comment by michuanhaohao** [comment]
![image](https://user-images.githubusercontent.com/23547900/62407642-3c4c7b80-b5ee-11e9-815b-30ba1176d888.png)

**Comment by MasterofPLM** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/23547900/62407642-3c4c7b80-b5ee-11e9-815b-30ba1176d888.png)

Is this SEResNet50 result with all tricks?

**Comment by michuanhaohao** [comment]
@MasterofPLM Yes.
