### ISSUE TITLE
pid2label

### ISSUE THREAD

**Issue by SunshineJZJ** [michuanhaohao/reid-strong-baseline#67]
@michuanhaohao 大神你好 请问在dataset/market1501.py 中的pid2label 是没有用到吗 还是dataset.append((img_path, pid, camid))应该缩进一下  

_def _process_dir(self, dir_path, relabel=False):
        img_paths = glob.glob(osp.join(dir_path, '*.jpg'))
        pattern = re.compile(r'([-\d]+)_c(\d)')

        pid_container = set()
        for img_path in img_paths:
            pid, _ = map(int, pattern.search(img_path).groups())
            if pid == -1: continue  # junk images are just ignored
            pid_container.add(pid)
        pid2label = {pid: label for label, pid in enumerate(pid_container)}

        dataset = []
        for img_path in img_paths:
            pid, camid = map(int, pattern.search(img_path).groups())
            if pid == -1: continue  # junk images are just ignored
            assert 0 <= pid <= 1501  # pid == 0 means background
            assert 1 <= camid <= 6
            camid -= 1  # index starts from 0
            if relabel: pid = pid2label[pid]
            dataset.append((img_path, pid, camid))
        return dataset_

**Comment by michuanhaohao** [comment]
![image](https://user-images.githubusercontent.com/23547900/62529955-3c5cad80-b872-11e9-9c0f-e52aa57a1141.png)


训练的时候用到了，只是两行合并到一行写了而已

**Comment by SunshineJZJ** [comment]
好蠢的问题  刚才没有反应过来  谢谢 谢谢
