### ISSUE TITLE
BNNeck

### ISSUE THREAD

**Issue by nationalflag** [michuanhaohao/reid-strong-baseline#7]
请问一下在特征向量后加一个BN层和直接单位向量化有什么区别呢？

**Comment by michuanhaohao** [comment]
@nationalflag 单位向量化是把feature约束到球面上，BN归一化是尽可能拉近feature每个维度的大小。BN并没有约束到球面上，而是在超球面的附近随机分布。我的观点是，对于triplet loss这些metric loss，feature分布的越自由越好，就是无约束的欧式空间。但是对于分类loss，因为学习的夹角距离，所以把特征约束到球面上比较好（SphereReID，SphereFace等工作都提供了类似的结论）。可以发现，做了单位归一化之后triplet loss的效果是会下降的，但是softmax loss又喜欢归一化，于是折中的BNNeck就是这样考虑的。triplet loss拥有还算比较自由的欧式空间，而softmax loss直连的feature在BN归一化之后也更加接近于球面分布。这是我们的想法初衷，只不过也只是我们的观点，还需要大家的认可和更多的证明
