### ISSUE TITLE
Question about pretrained models of ResNet_IBN_a

### ISSUE THREAD

**Issue by lipond** [michuanhaohao/reid-strong-baseline#70]
I downloaded the models from this link (https://github.com/XingangPan/IBN-Net) and they are like these: resnet50_ibn_a.pth.tar, resnet101_ibn_a.pth.tar. However, when I uncompress them using tar command, the output errors show they are not tar packages. So would you please tell how to use these pretrained models?

**Comment by michuanhaohao** [comment]
@lipond Hi, you can download the pre-trained weight at: [https://pan.baidu.com/s/1yEvkJBP0mmoLP-vGaAxdeA](https://pan.baidu.com/s/1yEvkJBP0mmoLP-vGaAxdeA)
