### ISSUE TITLE
where are othre pre-trained model?

### ISSUE THREAD

**Issue by murdockhou** [michuanhaohao/reid-strong-baseline#71]
Hi, thanks for your work. I only find link with pre-trained model `resnet-50` backbone, i want to test backbone `resnet-18`, so can you provide this model link? Thanks a lot~

**Comment by michuanhaohao** [comment]
When you run the code at the first time, you can get the pre-trained model (ImageNet) from torchvision automatically. You can train the resnet-18 on Market1501 by yourself.

**Comment by murdockhou** [comment]
thanks~
