### ISSUE TITLE
weird error for `hard_example_mining`

### ISSUE THREAD

**Issue by wjensheng** [michuanhaohao/reid-strong-baseline#73]
Hi team,

Thank you for sharing your work. I am currently facing an error for `hard_example_mining` while trying to implement your code and I could not identify what was wrong.

It worked for the 1st mini batch for my `train_loader` but during the 2nd mini batch, the following error occurred.  
```
line 392, in hard_example_mining
    dist_mat[is_pos].contiguous().view(N, -1), 1, keepdim=True)
RuntimeError: shape '[48, -1]' is invalid for input of size 52
```
After trying to run it the second time, it failed for the 1st mini batch and the error turned out to be 
```
line 392, in hard_example_mining
    dist_mat[is_pos].contiguous().view(N, -1), 1, keepdim=True)
RuntimeError: shape '[48, -1]' is invalid for input of size 50
``` 

I wonder why did both runs give different "invalid size" and how can I possibly trace where is the invalid size happening since I cannot find any 50 or 52 in the code?

Thank you.

**Comment by L1aoXingyu** [comment]
It seems something wrong in your dataloader. Have you changed any code?

**Comment by wjensheng** [comment]
Hi Xingyu, thanks for the response. My code works fine for the `center_loss` but fails for the `triplet_center_loss`. Would that still be an issue with my dataloader? Thanks, once again!

**Comment by L1aoXingyu** [comment]
Have you pass arg `sampler` in dataloader?

**Comment by wjensheng** [comment]
No I did not. Now I see the problem. Thank you!
