### ISSUE TITLE
关于损失函数

### ISSUE THREAD

**Issue by 2110317008** [michuanhaohao/reid-strong-baseline#74]
文中提到总的损失包含三个部分：Lid，Lt ，Lc。文中所述余弦距离能实现更好的性能比欧氏距离，问题一：在triple_loss中dP和dn的计算是由欧氏距离改变为余弦距离吗？原文： Cosine distance metric can achieve better performance than Euclidean distance metric. Experimental results
in Table. 1 show that BNNeck can improve performance of the ReID model by a large margin.
文中也说在训练阶段，ft和fi分别来计算triple_loss和ID loss，图5把我弄得有点晕，所以我想问
问题二：测试（inference）阶段和训练阶段都是由最初所说的三个损失的总和吗？原文：In this case, cosine distance is more suitable than Euclidean distance for the model optimized by ID loss in the inference stage.

**Comment by michuanhaohao** [comment]
你可以把center loss去掉，现在只有ID loss和triplet loss，训练的时候triplet loss是欧式距离。

测试阶段是没有loss的，但是有ft和fi两个特征，欧式距离和余弦距离都可以计算特征的距离，因此总共会有四个结果。这个结果是为了证明fi这个特征更适合用余弦距离

**Comment by 2110317008** [comment]
谢谢！明白了！

**Comment by 2110317008** [comment]
您好！再问一个问题。从M->D和从D_>M，就是如何在一个数据集上训练在另一个数据集上测试？
