### ISSUE TITLE
problem with dataset msmt17 and cuhk03

### ISSUE THREAD

**Issue by ln23415** [michuanhaohao/reid-strong-baseline#75]
hi mate, I try your code on the msmt17 and cuhk03 dataset, but I found some unexpected error. I don't have the 'splits_classic_detected.json', 'splits_classic_labeled.json' ... files in folder cuhk03/ but only 'cuhk03.mat'. what's more, in msmt17 dataset, I only got 'bounding_box_test', 'bounding_box_train' and 'query' folders, what should I do to gain other files?

**Comment by michuanhaohao** [comment]
You can refer here: [https://github.com/michuanhaohao/AlignedReID](url)

**Comment by ln23415** [comment]
oh, thanks~
