### ISSUE TITLE
Hash algorithms to match feature vectors

### ISSUE THREAD

**Issue by lynnw123** [michuanhaohao/reid-strong-baseline#78]
Thanks for sharing the training tricks, I am wondering how to do the feature vectors matching efficiently, any suggestions about the hash or other methods? thanks

**Comment by michuanhaohao** [comment]
We use pytorch to compute the L2 distance in the GPU. Some works focused on hash and person reid, but I am not familiar with it. You can refer to those works.

**Comment by lynnw123** [comment]
Thanks for the reply!
