### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by LilySys** [michuanhaohao/reid-strong-baseline#80]
罗博士，您好！
       当算map时，当gallery的类别数大于query的类别数时，算出来的结果map以及rank低到异常，如map：1.0%、rank-1：0.2%，当去掉gallery中与query不相同的类别时，算出来的map就恢复正常了，如map：93%，请问这是什么原因？

**Comment by michuanhaohao** [comment]
理论上不应该，正常的测试就是gallery类别数更大，因为有一个-1的ID，是一些背景图（干扰项）。可能有两个原因，你加入的那些图网络不认识，或者标注错误了。另外一个可能就是代码哪里出了小bug，不过这个也只能自己一步一步断点看一下

**Comment by LilySys** [comment]
好的，谢谢！
