### ISSUE TITLE
Have you tried bag of tricks on mobilenetv2?

### ISSUE THREAD

**Issue by amandayeyan** [michuanhaohao/reid-strong-baseline#81]

**Comment by michuanhaohao** [comment]
No, all backbones we tried are present as follow:
![image](https://user-images.githubusercontent.com/23547900/64223278-e6793500-cf05-11e9-84f7-feaf0c4cb443.png)

**Comment by amandayeyan** [comment]
> No, all backbones we tried are present as follow:
> ![image](https://user-images.githubusercontent.com/23547900/64223278-e6793500-cf05-11e9-84f7-feaf0c4cb443.png)

Ok. Thanks for the reply.

**Comment by nixingyang** [comment]
I re-implemented this algorithm and the mAP score using MobileNetV2 on the Market1501 dataset was around 0.64-0.65.

**Comment by michuanhaohao** [comment]
@nixingyang @amandayeyan 
Thanks!

Without these tricks, MobileNetV2 only achieves 56.3 mAP.
![image](https://user-images.githubusercontent.com/23547900/64930766-422cb200-d866-11e9-98c7-4c274a3d81c6.png)

**Comment by amandayeyan** [comment]
> @nixingyang @amandayeyan
> Thanks!
> 
> Without these tricks, MobileNetV2 only achieves 56.3 mAP.
> ![image](https://user-images.githubusercontent.com/23547900/64930766-422cb200-d866-11e9-98c7-4c274a3d81c6.png)

Just to double confirm that the said mAP 56.3% of MobileNetV2 was trained only with Market1501 training data? I am asking because if we fine-tune on ImageNet pretrained model, MobilenetV2 can achieve ~67% mAP.

**Comment by michuanhaohao** [comment]
@amandayeyan I consider you are right. 56.3% mAP is achieved without ImageNet pretrained model.

**Comment by immarioo** [comment]
> MobileNetV2

hello, i want to re-implement this algorithm using mobilenetv2 backbone, can you tell me more details, thanks.
