### ISSUE TITLE
    raise ValueError("Object should have `state_dict` method.")

### ISSUE THREAD

**Issue by ngocson1804** [michuanhaohao/reid-strong-baseline#84]
Hello,
your paper is very useful, but when I ran your source code. I got an error:
 "raise ValueError("Object should have `state_dict` method.")  ValueError: Object should have `state_dict` method"
could you please help me fix it. Thank you!

**Comment by michuanhaohao** [comment]
I have merged a PR. I think it has been resolved.

You can use ignite==0.1.2. ignite0.2.0 may result in some errors.
