### ISSUE TITLE
Where are Pretrained Models ?

### ISSUE THREAD

**Issue by lxtGH** [michuanhaohao/reid-strong-baseline#86]
Hi! Thanks for your great project. Where can I download trained model? (.pth files)

**Comment by TomKomar** [comment]
https://github.com/michuanhaohao/reid-strong-baseline#results-rank1map
below the tables

**Comment by lxtGH** [comment]
I know that place, but it looks strange, res50.pth only 2MB how possible

**Comment by TomKomar** [comment]
The .zip file is split into multiple small items. You have to download the whole folder, unpack the folder and then unpack the first one (it will join with data from others during extraction)

**Comment by michuanhaohao** [comment]
@lxtGH You should download all .zip files.

**Comment by lxtGH** [comment]
@michuanhaohao Hi Thanks for reply, but I extract all files from them but i can not get single file. How can I load in pytorch. Did I miss something?

**Comment by michuanhaohao** [comment]
Could you let me see your file? If you unpack all .zip files, you should get only one .pth model.

**Comment by lxtGH** [comment]
@michuanhaohao Hi! Thanks for your kind reply. I got it
