### ISSUE TITLE
could parameter of resnet50 pre-trained on imagenet transfer to resnet50_ibn 

### ISSUE THREAD

**Issue by SpiritBear000** [michuanhaohao/reid-strong-baseline#87]
when i add following code in [./model/baseline.py](https://github.com/michuanhaohao/reid-strong-baseline/blob/master/modeling/baseline.py)
```
if __name__ == "__main__":
    input = torch.autograd.Variable(torch.FloatTensor(torch.rand([50, 3, 320, 320]))).cuda()
    net = Baseline(10, 1, '/home/[name]/.torch/models/resnet50-19c8e357.pth',
                   'no', 'after', 'resnet50_ibn_a', 'imagenet')
    net = nn.DataParallel(net).cuda()
    output = net(input)
    print(output)
```

i got this error:
![捕获](https://user-images.githubusercontent.com/32519071/65769452-27abe000-e166-11e9-9f70-7ba079716e52.JPG)

**Comment by michuanhaohao** [comment]
No, you should download the pre-trained model of the ibn-net. Please check the Readme.
