### ISSUE TITLE
New Trick in Person reID

### ISSUE THREAD

**Issue by lulujianjie** [michuanhaohao/reid-strong-baseline#88]
Hi, I am creating this issue to share a new trick in person reID, the arcface loss.

As you mentioned in the README, I re-implemented a tiny [repo](https://github.com/lulujianjie/person-reid-tiny-baseline) by following your paper and code before. Recently, I test reID performance using SOTA metric loss in face recognition. Experimental result shows that [arcFace loss](https://github.com/lulujianjie/person-reid-tiny-baseline/blob/master/loss/arcface.py) can converge faster (around 50 epochs vs 100 epochs) and achieve slightly better performance (around 0.7%/0.9% improvement in rank1/mAP) than softmax+triplet loss+center loss.

Looking forward to your response and discussion.

**Comment by L1aoXingyu** [comment]
It's a very interesting result because we do some experiments about some face loss, such as cosface, arcface, but the result is a little bit bad. I will check your result first and we can discuss it later.

**Comment by L1aoXingyu** [comment]
I do some experiments for arcface and I get the result below

| loss | market1501 | dukemtmc |
| -- | -- | --  |
| cosface | 93.6 (83.7) | 84.6 (69.8) |
| arcface | 93.6 (84.1) | 84.9 (70.7) |

Actually, it is lower for the baseline(softmax+triplet), especially on duke 
| loss | market1501 | dukemtmc |
| -- | -- | --  |
| baseline | 94.6 (86.1) | 87.3 (76.0) |

Could you shed some light on this situation?

**Comment by lulujianjie** [comment]
> I do some experiments for arcface and I get the result below
> 
> loss	market1501	dukemtmc
> cosface	93.6 (83.7)	84.6 (69.8)
> arcface	93.6 (84.1)	84.9 (70.7)
> Actually, it is lower than the baseline(softmax+triplet), especially mAP on duke
> 
> loss	market1501	dukemtmc
> baseline	94.6 (86.1)	87.3 (76.0)
> Could you shed some light on this situation? @lulujianjie

Hi, Xingyu, which data sampler did you use in your experiment? In my experiment, triplet sampler, namely fixed number of identities and images per batch (8x8), achieves better results as I mentioned. The arcface using the default sampler achieves slightly lower performance than the baseline.

**Comment by L1aoXingyu** [comment]
I just follow your experiment setting, triplet sampler with 8x8. If I change it to 4x16, it will lead to a poor result.
BTW, I notice you change the bnneck to affine=False. 
Anything else I didn't notice?

**Comment by lulujianjie** [comment]
I also modified the data augmentation method in my repo. But it might not influence the results since the comparison experiments follow the same settings. I will test the arcface using your origin baseline code and report the result later.

**Comment by L1aoXingyu** [comment]
I noticed your result is 84.3 for mAP. Actually, it is lower than baseline result 86. Besides, mAP result is very bad on duke.

**Comment by lulujianjie** [comment]
> I noticed your result is 84.3 for mAP. Actually, it is lower than baseline result 86. Besides, mAP result is very bad on duke.

Hi, Xingyu. I tested the arcface using this repo. Here are the experimental results on Market1501.
|  | mAP | Rank1 |
| ------ | ------ | ------ |
| Baseline (this repo) | 85.8 | 94.2 |
| arcface+triplet sampler | 84.3 | 94.3 |
| ------ | ------ | ------ |
| Baseline (my repo) | 83.4 | 94.0 |
| arcface+triplet sampler | 84.3 | 94.7 |

The reason, as you mentioned, maybe that mAP of my repo is lower than this baseline. I will review my code and report it later. Thanks again for your kind discussion.
