### ISSUE TITLE
resnet50_ibn_a.pth can not download

### ISSUE THREAD

**Issue by visionxy** [michuanhaohao/reid-strong-baseline#90]
Can you give me a baidu cloud link? Thank you !

**Comment by michuanhaohao** [comment]
Hi, you can download the pre-trained weight at: https://pan.baidu.com/s/1yEvkJBP0mmoLP-vGaAxdeA

**Comment by visionxy** [comment]
Thank you very much!




------------------ 原始邮件 ------------------
发件人: "Hao Luo"<notifications@github.com>;
发送时间: 2019年10月10日(星期四) 上午9:57
收件人: "michuanhaohao/reid-strong-baseline"<reid-strong-baseline@noreply.github.com>;
抄送: "weili"<1538517531@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [michuanhaohao/reid-strong-baseline] resnet50_ibn_a.pth can notdownload (#90)




Hi, you can download the pre-trained weight at: https://pan.baidu.com/s/1yEvkJBP0mmoLP-vGaAxdeA
