### ISSUE TITLE
The test.py CANNOT find the trained checkpoints

### ISSUE THREAD

**Issue by luewu** [michuanhaohao/reid-strong-baseline#93]
Firstly, I trained the model:

`python3 tools/train.py --config_file='configs/softmax_triplet_with_center.yml' MODEL.DEVICE_ID "('your device id')" DATASETS.NAMES "('market1501')" OUTPUT_DIR "('trained-weight')"
`

Then I got the models' checkpoints:

`     (py36_ reid_ b1) roote iZuf 64yef 6g lm io8abuokpZ:~ /reid- strong-baseline# cd trained-weight `

`(py36_ reid_ b1) roote iZuf 64yef 6g lmio8abuokpZ: reid- strong-baseline/trained-weight# ls`

What I got are:

> log . txt  resnet50_ model_ 120. pth  resnet50_ optimizer_ 40 .pth  resnet50_ optimizer_ center_ 80 . pth resnet50_ center_ param_ 120.pth resnet50_ model_ 40. pth  resnet50_ optimizer.80.pth
> 
> resnet50_ center_ param_ 40. pth  resnet50_ model_ 80 . pth  resnet50_ optimizer_ center_ 120 . pth resnet50_ center_ param_ 80. pth  resnet50_ optimizer_ 120 .pth resnet50_ optimizer_ center_ 40 . pth

So I thought I got the checkpoints

And I tested the model:

`python3 tools/test.py --config_file='configs/softmax_triplet_with_center.yml' MODEL.DEVICE_ID "('0')" DATASETS.NAMES "('market1501')" TEST.NECK_FEAT "('after')" TEST.FEAT_NORM "('yes')" MODEL.PRETRAIN_CHOICE "('self')" TEST.WEIGHT "('trained-weight')"
`
But the test was failed:

> Traceback (most recent call last):
> File 'tools/test.py", line 67, in <module>
>  main()
> File tools/test.py", line 61,in main 
> model.load _paran(cfg.TEST.WEIGHT)
> File "./nodeling/baseline.py",line 175,in load_param 
> param _dict = torch.load(trained_path)
> File "/usr/local/anaconda/enus/py36_reid_b1/lib/puthon3.6/site-packages/torch/serializat tion.py",line 381,in load 
> f = open(f,'rb')
> IsADirectoryError: [Errno 21] Is a directory:'trained weight'

I thougt it might becuse 'trained-weight' is a directory, and maybe I  should use a file.

Then I test like this:
`python3 tools/test.py --config_file='configs/softmax_triplet_with_center.yml' MODEL.DEVICE_ID "('0')" DATASETS.NAMES "('market1501')" TEST.NECK_FEAT "('after')" TEST.FEAT_NORM "('yes')" MODEL.PRETRAIN_CHOICE "('self')" TEST.WEIGHT "('trained-weight'/resent50_optimizer_center_120.pth')"`

But also failed:

> Traceback (most recent call last):
> File 'tools/test.py", line 67, in <module>
>  main()
> File tools/test.py", line 61,in main 
> model.load _paran(cfg.TEST.WEIGHT)
> File "./nodeling/baseline.py",line 176,in load_param 
> for i in param_dict:
> TypeEoor: 'SGD'  object is not iterable

I have checked the problem in Internet, but I still didn't slove it.

Please tell me what should I do next.

Thank you very much!!!

**Comment by luewu** [comment]
Thanks a lot for your reading and great work!

**Comment by michuanhaohao** [comment]
"('trained-weight'/resent50_optimizer_center_120.pth')"

**Comment by michuanhaohao** [comment]
"('trained-weight'/resent50_optimizer_center_120.pth')"

**Comment by michuanhaohao** [comment]
"('trained-weight'/resent50_optimizer_center_120.pth')"

I consider the path is error. 

Try "(trained-weight/resent50_optimizer_center_120.pth')"

**Comment by PAUPAUPAUL** [comment]
I get the same trouble  now, did you find the solution ?

**Comment by PAUPAUPAUL** [comment]
> "('trained-weight'/resent50_optimizer_center_120.pth')"
> I consider the path is error.
> Try "(trained-weight/resent50_optimizer_center_120.pth')"

I think is not the problem of the path, otherwise we will have the problem below:
FileNotFoundError: [Errno 2] No such file or directory: ......

**Comment by michuanhaohao** [comment]
python3 tools/test.py --config_file='configs/softmax_triplet.yml' MODEL.DEVICE_ID "('0')" DATASETS.NAMES "('market1501')" TEST.NECK_FEAT "('after')" TEST.FEAT_NORM "('yes')" MODEL.PRETRAIN_CHOICE "('self')" DATASETS.ROOT_DIR "('/home/admin/workspace/shared/xunji/')" OUTPUT_DIR "('/home/admin/workspace/shared/log/market/triplet_rea')" TEST.WEIGHT "('/home/admin/workspace/shared/log/market/triplet_rea/resnet50_model_120.pth')"

**Comment by michuanhaohao** [comment]
Please use the model checkpoint. You used the optimizer checkpoint.
