### ISSUE TITLE
when load the pre-trained model

### ISSUE THREAD

**Issue by 704051419** [michuanhaohao/reid-strong-baseline#94]
` File "./modeling/backbones/resnet.py", line 140, in load_param
    self.state_dict()[i].copy_(param_dict[i])
KeyError: 'layer1.0.bn1.IN.weight'`
why?

**Comment by zhanghongruiupup** [comment]
Have you solved it?

**Comment by L1aoXingyu** [comment]
you need to load ibn pretrained model if you set the backbone to ibn.

**Comment by zhanghongruiupup** [comment]
> 如果将主干设置为ibn，则需要加载ibn预训练模型。



> you need to load ibn pretrained model if you set the backbone to ibn.

I already set _C.MODEL.PRETRAIN_PATH="xxxxx/r50_ibn_a.pth'",still this error.thanks your reply.

**Comment by zhanghongruiupup** [comment]
> you need to load ibn pretrained model if you set the backbone to ibn.

I already set _C.MODEL.PRETRAIN_PATH="xxxxx/r50_ibn_a.pth'",still this error.thanks your reply.

**Comment by L1aoXingyu** [comment]
have you set your backbone to ibn?

**Comment by zhanghongruiupup** [comment]
> have you set your backbone to ibn?

The problem is solved，I used to resnet50,now set resnet50_ibn_a.
Thanks.Good people are safe in their lives

**Comment by yiintong** [comment]
how to solved？Can you give me a advice

**Comment by yiintong** [comment]
> > have you set your backbone to ibn?
> 
> The problem is solved，I used to resnet50,now set resnet50_ibn_a.
> Thanks.Good people are safe in their lives

I still have the problem

**Comment by 704051419** [comment]
@yiintong not konwing why. i just set the resnet50_ibn_a, then it works.

**Comment by yiintong** [comment]
I have keyerror problem  
pytorch1.31 python 3.74
'layer1.0.bn1.IN.weight'

resnet 50

**Comment by 704051419** [comment]
My environment is torch0.4 and python3.6





------------------ Original ------------------

**Comment by yiintong** [comment]
![image](https://user-images.githubusercontent.com/28750869/69770565-7c9abf80-11c4-11ea-8be3-29898506b985.png)
this is my problem.
it exits in resnet.py

**Comment by yiintong** [comment]
> My environment is torch0.4 and python3.6
> […](#)
> ------------------ Original ------------------ From: Yxt <notifications@github.com&gt; Date: Thu,Nov 28,2019 9:46 AM To: michuanhaohao/reid-strong-baseline <reid-strong-baseline@noreply.github.com&gt; Cc: 张淼 <704051419@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [michuanhaohao/reid-strong-baseline] when load the pre-trained model (#94) I have keyerror problem pytorch1.31 python 3.74 'layer1.0.bn1.IN.weight' resnet 50 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

thanks a lot ,can you help me look this picture

**Comment by yiintong** [comment]
Can I have 

> My environment is torch0.4 and python3.6
> […](#)
> ------------------ Original ------------------ From: Yxt <notifications@github.com&gt; Date: Thu,Nov 28,2019 9:46 AM To: michuanhaohao/reid-strong-baseline <reid-strong-baseline@noreply.github.com&gt; Cc: 张淼 <704051419@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [michuanhaohao/reid-strong-baseline] when load the pre-trained model (#94) I have keyerror problem pytorch1.31 python 3.74 'layer1.0.bn1.IN.weight' resnet 50 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Can I get your contact information easily?

**Comment by mhiyer** [comment]
> ![image](https://user-images.githubusercontent.com/28750869/69770565-7c9abf80-11c4-11ea-8be3-29898506b985.png)
> this is my problem.
> it exits in resnet.py

Why don't you simply use torch.load(model_path) in tools/test.py instead of changing the load_params function?
