### ISSUE TITLE
Question about triplet_sampler

### ISSUE THREAD

**Issue by Ernie1** [michuanhaohao/reid-strong-baseline#96]
https://github.com/michuanhaohao/reid-strong-baseline/blob/0a682176ad6306512bca3f6a1e283aa244247a77/data/samplers/triplet_sampler.py#L66
```
for pid in selected_pids:
    batch_idxs = batch_idxs_dict[pid].pop(0)
    final_idxs.extend(batch_idxs)
```
Hi, thank you for your excellent job. I am confused why you use `pop(0)` instead of `pop()` which is much faster.
`idxs` are already shuffled, I think their effects are identical.

**Comment by michuanhaohao** [comment]
Thank you for your suggestions. I will try it after CVPR2020 deadline. 

o(╥﹏╥)o

**Comment by Ernie1** [comment]
You're welcome!

**Comment by Luffy03** [comment]
> 别客气！

kiang
