### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by zhanghongruiupup** [michuanhaohao/reid-strong-baseline#97]
Thank you for providing the code, but I encountered an error during training.I set PRETRAIN_PATH="/home/fwq/zhanghongruils/reid-strong-baseline-master/r50_ibn_a.pth".   
OUTPUT_DIR="/home/fwq/zhanghongruils/reid-strong-baseline-master/result"
Then get :
    self.state_dict()[i].copy_(param_dict[i])
KeyError: 'layer1.0.bn1.IN.weight'

hope to get answers，thanks.

**Comment by yiintong** [comment]
environment windows
pytorch 1.31
I still have the problem

**Comment by mhiyer** [comment]
You could try to use torch.load(model_path) instead of using their load_params function.
I had the same issue, this worked.
