### ISSUE TITLE
Data enhancement

### ISSUE THREAD

**Issue by jerry-chenrb** [michuanhaohao/reid-strong-baseline#98]
Thank you very much for the author's contribution to reid. As a beginner, I have benefited a lot. I asked how to run on my own data set before. Thank you for your reply. I realized it, and rank 1 = 77%. Compared with market1501, the number of pictures of each PID in my data set is less. I tried to do some flipping, but it seems that you have done this work, right? Can you give me some suggestions for promotion, thank you

**Comment by michuanhaohao** [comment]
Hi, CUHK03 is smaller than Market1501. However, the rank-1 of CUHK is only 70~80% with the same evaluation protocol. Because the image quantity is worse and the training data is less.
